// Community + Nebius-corporate events.
// Seeded from nebius-builders repo #1 (src/lib/mock.ts EVENTS + OFFICIAL_EVENTS).
// These extend the marketing-only `events` list in data.ts with the builder-hosted
// rows the /events directory needs.

export type BuilderEventFormat =
  | "WORKSHOP"
  | "TALK"
  | "HACKATHON"
  | "OFFICE_HOURS"
  | "DEMO_NIGHT"
  | "OTHER";

export type BuilderEventStatus = "DRAFT" | "PUBLISHED" | "COMPLETED" | "CANCELLED";

export type BuilderEvent = {
  id: string;
  title: string;
  description: string;
  format: BuilderEventFormat;
  startsAt: string;
  endsAt: string;
  timezone: string;
  venueName: string;
  venueAddress?: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  isOnline: boolean;
  expectedAttendees?: number;
  actualAttendees?: number;
  productFocus: string[];
  builderHandle: string;
  builderName: string;
  status: BuilderEventStatus;
  lumaUrl?: string;
  isOfficial?: boolean;
  officialUrl?: string;
  dateRange?: string;
};

export const builderEvents: BuilderEvent[] = [
  {
    id: "e_1",
    title: "Fine-tuning Gemma on Nebius — Hands-on",
    description:
      "QLoRA fine-tune Gemma 4 on your own data. Bring a laptop, leave with a deployed adapter.",
    format: "WORKSHOP",
    startsAt: "2026-05-12T19:00:00Z",
    endsAt: "2026-05-12T22:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "Sandbox VR SF",
    venueAddress: "833 Market St, San Francisco, CA",
    city: "San Francisco",
    country: "US",
    lat: 37.7847,
    lng: -122.4072,
    isOnline: false,
    expectedAttendees: 30,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "rayyanzahid",
    builderName: "Ray Zahid",
    status: "PUBLISHED",
    lumaUrl: "https://lu.ma/example-fine-tune",
  },
  {
    id: "e_2",
    title: "LLM Evals — A Workshop for Builders",
    description: "How to actually measure if your fine-tune is better. With Token Factory examples.",
    format: "WORKSHOP",
    startsAt: "2026-05-15T23:00:00Z",
    endsAt: "2026-05-16T01:00:00Z",
    timezone: "America/New_York",
    venueName: "Newlab Brooklyn",
    venueAddress: "19 Morris Ave, Brooklyn, NY",
    city: "Brooklyn",
    country: "US",
    lat: 40.7008,
    lng: -73.9787,
    isOnline: false,
    expectedAttendees: 50,
    productFocus: ["tokenfactory"],
    builderHandle: "aboros",
    builderName: "Alex Boros",
    status: "PUBLISHED",
    lumaUrl: "https://lu.ma/example-evals",
  },
  {
    id: "e_3",
    title: "GPU Cluster Office Hours",
    description: "Bring your Slurm / Soperator questions. Drop-in style. Free pizza.",
    format: "OFFICE_HOURS",
    startsAt: "2026-05-20T17:00:00Z",
    endsAt: "2026-05-20T19:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "Stanford CodeX",
    venueAddress: "Stanford, CA",
    city: "Palo Alto",
    country: "US",
    lat: 37.4275,
    lng: -122.1697,
    isOnline: false,
    expectedAttendees: 25,
    productFocus: ["aicloud", "soperator"],
    builderHandle: "jwen",
    builderName: "Jia Wen",
    status: "PUBLISHED",
  },
  {
    id: "e_4",
    title: "Berlin Builders Meetup #4",
    description: "Token Factory show-and-tell. Bring a demo. Drinks after.",
    format: "DEMO_NIGHT",
    startsAt: "2026-05-22T18:00:00Z",
    endsAt: "2026-05-22T22:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "Factory Berlin",
    venueAddress: "Lohmühlenstraße 65, Berlin",
    city: "Berlin",
    country: "DE",
    lat: 52.4985,
    lng: 13.4467,
    isOnline: false,
    expectedAttendees: 80,
    productFocus: ["tokenfactory"],
    builderHandle: "skoshy",
    builderName: "Sarah Koshy",
    status: "PUBLISHED",
    lumaUrl: "https://lu.ma/example-berlin",
  },
  {
    id: "e_5",
    title: "Tokyo Agents Hackathon",
    description: "8-hour build session. Top demo wins $500 of Nebius credits.",
    format: "HACKATHON",
    startsAt: "2026-05-25T01:00:00Z",
    endsAt: "2026-05-25T09:00:00Z",
    timezone: "Asia/Tokyo",
    venueName: "Roppongi Hills",
    venueAddress: "Roppongi, Tokyo",
    city: "Tokyo",
    country: "JP",
    lat: 35.6604,
    lng: 139.7292,
    isOnline: false,
    expectedAttendees: 60,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "fnakamura",
    builderName: "Fumi Nakamura",
    status: "PUBLISHED",
  },
  {
    id: "e_6",
    title: "Soperator Deep Dive (Online)",
    description:
      "Live walkthrough of running production agent fleets on Soperator. Q&A throughout.",
    format: "TALK",
    startsAt: "2026-05-28T16:00:00Z",
    endsAt: "2026-05-28T17:30:00Z",
    timezone: "America/Chicago",
    venueName: "Online — Zoom",
    isOnline: true,
    city: "Online",
    country: "US",
    lat: 30.2672,
    lng: -97.7431,
    expectedAttendees: 200,
    productFocus: ["soperator"],
    builderHandle: "dperez",
    builderName: "Daniel Perez",
    status: "PUBLISHED",
  },
  {
    id: "e_7",
    title: "Cairo AI Founder Mixer",
    description: "Founder-only mixer for Arabic NLP and MENA AI startups.",
    format: "OTHER",
    startsAt: "2026-05-30T17:00:00Z",
    endsAt: "2026-05-30T20:00:00Z",
    timezone: "Africa/Cairo",
    venueName: "AmCham Cairo",
    venueAddress: "Cairo",
    city: "Cairo",
    country: "EG",
    lat: 30.0444,
    lng: 31.2357,
    isOnline: false,
    expectedAttendees: 40,
    productFocus: ["tokenfactory"],
    builderHandle: "ehassan",
    builderName: "Esra Hassan",
    status: "PUBLISHED",
  },
  {
    id: "e_8",
    title: "Sandbox VR SF — Fine-tuning Workshop",
    description: "30 attendees fine-tuned Gemma live. The original.",
    format: "WORKSHOP",
    startsAt: "2026-05-05T19:00:00Z",
    endsAt: "2026-05-05T22:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "Sandbox VR SF",
    city: "San Francisco",
    country: "US",
    lat: 37.7847,
    lng: -122.4072,
    isOnline: false,
    expectedAttendees: 30,
    actualAttendees: 31,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "rayyanzahid",
    builderName: "Ray Zahid",
    status: "COMPLETED",
  },
  // ===== Imported from luma.com/NebiusAI (2026-05-13) =====
  {
    id: "luma_paxjj7qo",
    title: "Agents, after dark — Tavily × CopilotKit × Nebius",
    description: "Evening mixer for builders shipping agents. Drinks, lightning demos, and an excuse to compare prompts in person.",
    format: "OTHER",
    startsAt: "2026-05-15T01:30:00Z",
    endsAt: "2026-05-15T04:30:00Z",
    timezone: "America/Los_Angeles",
    venueName: "San Francisco (private venue)",
    city: "San Francisco",
    country: "US",
    lat: 37.7749,
    lng: -122.4194,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "tavily",
    builderName: "Tavily, CopilotKit & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/paxjj7qo",
  },
  {
    id: "luma_sg126t3h",
    title: "Ultimate Bots: Fight × Dance — powered by Nebius",
    description: "Bring a bot, watch it brawl, watch it boogie. Wildly unserious format with very serious infrastructure underneath.",
    format: "DEMO_NIGHT",
    startsAt: "2026-05-15T02:00:00Z",
    endsAt: "2026-05-15T06:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "SoMa, San Francisco",
    city: "San Francisco",
    country: "US",
    lat: 37.7749,
    lng: -122.4194,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "xenia",
    builderName: "Xenia Bulatov",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/sg126t3h",
  },
  {
    id: "luma_paris_hack",
    title: "{Tech: Europe} Paris AI Hackathon",
    description: "One-day Paris hackathon for European AI builders. Token Factory credits + an engineer on the floor for technical help.",
    format: "HACKATHON",
    startsAt: "2026-05-16T07:30:00Z",
    endsAt: "2026-05-16T19:00:00Z",
    timezone: "Europe/Paris",
    venueName: "Paris (TBA)",
    city: "Paris",
    country: "FR",
    lat: 48.8566,
    lng: 2.3522,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "techeurope",
    builderName: "{Tech: Europe}",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/paris-hack",
  },
  {
    id: "luma_gkcqiq84",
    title: "HackwithSeattle",
    description: "Seattle hackathon with Nebius credits + on-site support. Bring a laptop, ship something demo-ready by close.",
    format: "HACKATHON",
    startsAt: "2026-05-21T16:00:00Z",
    endsAt: "2026-05-22T00:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "Seattle (TBA)",
    city: "Seattle",
    country: "US",
    lat: 47.6062,
    lng: -122.3321,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "aviral",
    builderName: "Aviral & co-hosts",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/gkcqiq84",
  },
  {
    id: "luma_1rna5bdp",
    title: "Builders & Brews London",
    description: "London co-working drop-in for AI builders at Encode Hub. Coffee on, laptops out, Nebius credits available for the room.",
    format: "OFFICE_HOURS",
    startsAt: "2026-05-22T08:00:00Z",
    endsAt: "2026-05-22T17:00:00Z",
    timezone: "Europe/London",
    venueName: "Encode Hub",
    venueAddress: "London",
    city: "London",
    country: "GB",
    lat: 51.5074,
    lng: -0.1278,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "tavily",
    builderName: "Tavily, Encode Club & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/1rna5bdp",
  },
  {
    id: "luma_bvvrlgam",
    title: "build fridays london — work on your startup alongside others",
    description: "Friday co-working session in London for early-stage AI founders. Bring your laptop, bring your repo, leave with progress.",
    format: "OFFICE_HOURS",
    startsAt: "2026-05-22T15:00:00Z",
    endsAt: "2026-05-22T22:00:00Z",
    timezone: "Europe/London",
    venueName: "London",
    city: "London",
    country: "GB",
    lat: 51.5074,
    lng: -0.1278,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "aibeavers",
    builderName: "AI Beavers",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/bvvrlgam",
  },
  {
    id: "luma_bhfumnou",
    title: "Vibe coding at the Science Museum with ElevenLabs",
    description: "Evening hands-on session at the Science Museum. ElevenLabs voice + Token Factory inference; ship a working voice agent in two and a half hours.",
    format: "WORKSHOP",
    startsAt: "2026-05-22T18:00:00Z",
    endsAt: "2026-05-22T20:30:00Z",
    timezone: "Europe/London",
    venueName: "Science Museum, London",
    city: "London",
    country: "GB",
    lat: 51.4978,
    lng: -0.1745,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "elevenlabs",
    builderName: "ElevenLabs & Tavily",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/bhfumnou",
  },
  {
    id: "luma_fpxsdfhl",
    title: "Builders & Brews Berlin",
    description: "Berlin co-working session at St. Oberholz. Talk to other AI builders, get unstuck on your stack, claim Token Factory credits.",
    format: "OFFICE_HOURS",
    startsAt: "2026-05-27T07:00:00Z",
    endsAt: "2026-05-27T16:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "St. Oberholz, Berlin",
    city: "Berlin",
    country: "DE",
    lat: 52.52,
    lng: 13.405,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "tavily",
    builderName: "Tavily, n8n & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/fpxsdfhl",
  },
  {
    id: "luma_ma5bfzes",
    title: "Voice Agent Build Night — ElevenLabs × Tavily × Nebius",
    description: "Two-hour build night in Midtown for voice agents. ElevenLabs handles TTS/STT, Tavily handles search, Token Factory handles the brain.",
    format: "WORKSHOP",
    startsAt: "2026-05-28T21:30:00Z",
    endsAt: "2026-05-28T23:30:00Z",
    timezone: "America/New_York",
    venueName: "1350 Broadway, New York",
    city: "New York",
    country: "US",
    lat: 40.7528,
    lng: -73.9874,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "tavily",
    builderName: "Tavily, ElevenLabs & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/ma5bfzes",
  },
  {
    id: "luma_juded1wb",
    title: "Enterprise Agents Unleashed: Berlin Hackathon",
    description: "Berlin hackathon focused on enterprise-grade agent patterns — auth, observability, multi-tenant — with Nebius credits and on-site engineering support.",
    format: "HACKATHON",
    startsAt: "2026-05-29T08:00:00Z",
    endsAt: "2026-05-29T16:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "Berlin (TBA)",
    city: "Berlin",
    country: "DE",
    lat: 52.52,
    lng: 13.405,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw", "aicloud"],
    builderHandle: "tavily",
    builderName: "Tavily, Gradium & Nebius for Startups",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/juded1wb",
  },
  {
    id: "luma_biohack_nyc",
    title: "BioHack NYC: NextGen BioAgents",
    description: "Bio × AI hackathon in NYC. Build agents for protein design, lab automation, and clinical workflows; Nebius supplies compute for the heavy lifts.",
    format: "HACKATHON",
    startsAt: "2026-05-30T13:00:00Z",
    endsAt: "2026-05-31T01:00:00Z",
    timezone: "America/New_York",
    venueName: "New York (TBA)",
    city: "New York",
    country: "US",
    lat: 40.7128,
    lng: -74.006,
    isOnline: false,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "biohack",
    builderName: "Nucleate BioHack",
    status: "PUBLISHED",
    lumaUrl: "https://www.nucleatebiohack.org/",
  },
  {
    id: "luma_niv7ff32",
    title: "CiudadanIA CREA+ CDMX",
    description: "Mexico City builder gathering at Centro Cultural Futurama. Spanish-language session for AI builders shipping civic and public-good projects.",
    format: "OTHER",
    startsAt: "2026-05-30T14:00:00Z",
    endsAt: "2026-05-31T00:00:00Z",
    timezone: "America/Mexico_City",
    venueName: "Centro Cultural Futurama, CDMX",
    city: "Ciudad de México",
    country: "MX",
    lat: 19.4326,
    lng: -99.1332,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "geraldine",
    builderName: "Geraldine Masso",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/niv7ff32",
  },
  {
    id: "luma_place_holder_hack",
    title: "Applied Intelligence Hackathon",
    description: "Overnight applied-AI hackathon at Frontier Tower in San Francisco. Token Factory credits handed out at registration; demos at 7am.",
    format: "HACKATHON",
    startsAt: "2026-05-31T16:00:00Z",
    endsAt: "2026-06-01T03:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "Frontier Tower (Spaceship), 995 Market St",
    venueAddress: "995 Market St, San Francisco, CA",
    city: "San Francisco",
    country: "US",
    lat: 37.7831,
    lng: -122.4075,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "frontiertower",
    builderName: "Frontier Tower & Lynkable",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/place-holder-hack",
  },
  {
    id: "luma_sbxje1du",
    title: "Agentic Commerce: Build Day @ NY Tech Week",
    description: "NY Tech Week build day for agentic commerce — checkout agents, refund agents, fraud-screening agents. Tavily for search, Nebius for inference.",
    format: "WORKSHOP",
    startsAt: "2026-06-02T13:00:00Z",
    endsAt: "2026-06-02T21:00:00Z",
    timezone: "America/New_York",
    venueName: "NY Tech Week venue (TBA)",
    city: "New York",
    country: "US",
    lat: 40.7128,
    lng: -74.006,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "tavily",
    builderName: "Tavily & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/sbxje1du",
  },
  {
    id: "luma_zemh10km",
    title: "Agentic AI Hackathon — San Francisco",
    description: "Day-long agentic AI hackathon at AWS Builder Loft. Nebius co-sponsoring with credits + a branded track prize.",
    format: "HACKATHON",
    startsAt: "2026-06-05T16:00:00Z",
    endsAt: "2026-06-06T00:00:00Z",
    timezone: "America/Los_Angeles",
    venueName: "AWS Builder Loft, 525 Market St",
    venueAddress: "525 Market St, San Francisco, CA",
    city: "San Francisco",
    country: "US",
    lat: 37.7901,
    lng: -122.4015,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "aviral",
    builderName: "Aviral, AWS Builder Loft & Nebius",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/zemh10km",
  },
  {
    id: "luma_rtsospm5",
    title: "From Data to Decisions: Build a Market Research Agent",
    description: "Two-hour workshop at JP Morgan in NYC. Build a market-research agent over Token Factory inference and Tavily web search.",
    format: "WORKSHOP",
    startsAt: "2026-06-05T20:00:00Z",
    endsAt: "2026-06-05T22:00:00Z",
    timezone: "America/New_York",
    venueName: "JP Morgan Chase, New York",
    city: "New York",
    country: "US",
    lat: 40.7549,
    lng: -73.9707,
    isOnline: false,
    productFocus: ["tokenfactory"],
    builderHandle: "tavily",
    builderName: "Tavily",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/rtsospm5",
  },
  {
    id: "luma_munich_hackathon",
    title: "{Tech: Europe} Munich AI Hackathon",
    description: "Two-day Munich hackathon at Tacto for European AI builders. Token Factory credits + Nebius engineering support across both days.",
    format: "HACKATHON",
    startsAt: "2026-06-13T08:00:00Z",
    endsAt: "2026-06-14T16:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "Tacto, Munich",
    city: "Munich",
    country: "DE",
    lat: 48.1351,
    lng: 11.582,
    isOnline: false,
    productFocus: ["tokenfactory", "openclaw"],
    builderHandle: "techeurope",
    builderName: "{Tech: Europe}",
    status: "PUBLISHED",
    lumaUrl: "https://luma.com/munich-hackathon",
  },
];

// Nebius corporate events scraped from nebius.com/events on 2026-05-06.
export const officialEvents: BuilderEvent[] = [
  {
    id: "off_robotour",
    title: "Nebius RoboTour",
    description:
      "A global series of gatherings across research labs, startup hubs, and industry moments — connecting the people solving the hardest problems in robotics and physical AI.",
    format: "OTHER",
    startsAt: "2026-04-01T00:00:00Z",
    endsAt: "2026-12-31T23:59:00Z",
    timezone: "UTC",
    venueName: "Multiple cities (global tour)",
    city: "Global",
    country: "ZZ",
    lat: 0,
    lng: 0,
    isOnline: false,
    productFocus: ["aicloud"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/robotour",
    dateRange: "Apr 1 – Dec 31, 2026",
  },
  {
    id: "off_build_london",
    title: "Nebius.Build / London",
    description:
      "London stop of the Nebius.Build technical tour. Six hours of sessions for ML engineers, platform architects, and founders running AI in production — training, inference, observability, and the operations layer that holds it all together.",
    format: "OTHER",
    startsAt: "2026-05-21T11:00:00Z",
    endsAt: "2026-05-21T17:00:00Z",
    timezone: "Europe/London",
    venueName: "LABS House, London",
    city: "London",
    country: "GB",
    lat: 51.5074,
    lng: -0.1278,
    isOnline: false,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/nebius-build-london",
    lumaUrl: "https://luma.com/9xuza5he",
    dateRange: "May 21, 2026",
  },
  {
    id: "off_applied_ai_berlin",
    title: "Applied AI Conference by {Tech: Europe} 2026",
    description:
      "Find us at Applied AI Conference by {Tech: Europe}, 28 May — a one-day conference in Berlin for engineers, CTOs, and teams building and running AI systems in production.",
    format: "TALK",
    startsAt: "2026-05-28T09:00:00Z",
    endsAt: "2026-05-28T18:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "Berlin (TBA)",
    city: "Berlin",
    country: "DE",
    lat: 52.52,
    lng: 13.405,
    isOnline: false,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/applied-ai-conference-by-tech-europe-2026",
    dateRange: "May 28, 2026",
  },
  {
    id: "off_icra_2026",
    title: "ICRA 2026",
    description:
      "IEEE International Conference on Robotics and Automation (ICRA) 2026. Nebius will participate as an exhibitor and speaker, showcasing how modern AI infrastructure powers the next generation of robotics, Physical AI, and autonomous systems.",
    format: "TALK",
    startsAt: "2026-06-01T09:00:00Z",
    endsAt: "2026-06-05T18:00:00Z",
    timezone: "Europe/Vienna",
    venueName: "Vienna (TBA)",
    city: "Vienna",
    country: "AT",
    lat: 48.2082,
    lng: 16.3738,
    isOnline: false,
    productFocus: ["aicloud"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/icra-2026",
    dateRange: "Jun 1–5, 2026",
  },
  {
    id: "off_inflection",
    title: "Nebius Inflection",
    description:
      "An exclusive invite-only gathering of AI thought leaders, builders, operators, and investors, working at the frontier of AI and beyond.",
    format: "OTHER",
    startsAt: "2026-06-09T17:00:00Z",
    endsAt: "2026-06-09T22:00:00Z",
    timezone: "America/New_York",
    venueName: "USA (TBA)",
    city: "New York",
    country: "US",
    lat: 40.7128,
    lng: -74.006,
    isOnline: false,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/nebius-inflection",
    dateRange: "Jun 9, 2026",
  },
  {
    id: "off_ai_summit_london",
    title: "AI Summit London 2026",
    description:
      "Nebius is proud to be an Industry Partner at AI Summit London 2026. The headline AI event of London Tech Week, AI Summit London unites the UK and Europe's most innovative technologists and business leaders to explore AI's transformative real-world applications.",
    format: "TALK",
    startsAt: "2026-06-10T09:00:00Z",
    endsAt: "2026-06-11T18:00:00Z",
    timezone: "Europe/London",
    venueName: "London (TBA)",
    city: "London",
    country: "GB",
    lat: 51.5074,
    lng: -0.1278,
    isOnline: false,
    productFocus: ["aicloud"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/ai-summit-london-2026",
    dateRange: "Jun 10–11, 2026",
  },
  {
    id: "off_mlcon_munich",
    title: "MLcon Munich 2026",
    description:
      "Find us at ML Conference Munich 2026, June 25–26 — a leading conference for Generative AI and Machine Learning engineering, bringing together developers, ML engineers, architects, and AI practitioners working on real-world AI systems.",
    format: "TALK",
    startsAt: "2026-06-25T09:00:00Z",
    endsAt: "2026-06-26T18:00:00Z",
    timezone: "Europe/Berlin",
    venueName: "Munich (TBA)",
    city: "Munich",
    country: "DE",
    lat: 48.1351,
    lng: 11.582,
    isOnline: false,
    productFocus: ["aicloud", "tokenfactory"],
    builderHandle: "nebius",
    builderName: "Nebius",
    status: "PUBLISHED",
    isOfficial: true,
    officialUrl: "https://nebius.com/events/mlcon-munich-2026",
    dateRange: "Jun 25–26, 2026",
  },
];

const formatLabel: Record<BuilderEventFormat, string> = {
  WORKSHOP: "Workshop",
  TALK: "Talk",
  HACKATHON: "Hackathon",
  OFFICE_HOURS: "Office hours",
  DEMO_NIGHT: "Demo night",
  OTHER: "Event",
};

export function eventFormatLabel(f: BuilderEventFormat): string {
  return formatLabel[f];
}

export function publishedBuilderEvents(): BuilderEvent[] {
  return [...officialEvents, ...builderEvents.filter((e) => e.status === "PUBLISHED")].sort(
    (a, b) => +new Date(a.startsAt) - +new Date(b.startsAt),
  );
}

export function completedBuilderEvents(): BuilderEvent[] {
  return builderEvents.filter((e) => e.status === "COMPLETED");
}

export function findBuilderEvent(id: string): BuilderEvent | undefined {
  return [...builderEvents, ...officialEvents].find((e) => e.id === id);
}
