// Auto-scraped from github.com/nebius public repos (org-original only,
// forks like cilium/temporal excluded). 111 unique contributors as of
// the 2026-05-13 scrape. Re-run via the scrape script in /scripts/.
//
// Each row: github login, optional real name, total commits across all
// Nebius-original repos, and the repo→commit-count list (sorted desc).

export type NebiusContributor = {
  login: string;
  name: string;
  commits: number;
  repos: { repo: string; commits: number }[];
  location?: string;
  bio?: string;
  company?: string;
  twitter?: string;
};

export const nebiusContributors: NebiusContributor[] = [
  { login: "asteny", name: "Pavel Sofrony", commits: 1296, repos: [{ repo: "soperator", commits: 716 }, { repo: "slurm-deb-packages", commits: 245 }, { repo: "ml-containers", commits: 144 }, { repo: "nebius-solutions-library", commits: 113 }, { repo: "soperator-terraform", commits: 61 }, { repo: "slurm-plugins", commits: 12 }, { repo: "helmrelease-trigger-operator", commits: 3 }, { repo: "slurm-exporter", commits: 2 }], location: "Amsterdam, Netherlands", company: "Nebius" },
  { login: "Uburro", name: "Grigory Rochev", commits: 1045, repos: [{ repo: "soperator", commits: 768 }, { repo: "nebius-solutions-library", commits: 213 }, { repo: "helmrelease-trigger-operator", commits: 40 }, { repo: "soperator-terraform", commits: 23 }, { repo: "ml-containers", commits: 1 }], location: "The Hague, Netherlands" },
  { login: "dstaroff", name: "Dmitry Starov", commits: 839, repos: [{ repo: "soperator", commits: 423 }, { repo: "nebius-solutions-library", commits: 237 }, { repo: "soperator-terraform", commits: 117 }, { repo: "slurm-plugins", commits: 43 }, { repo: "slurm-deb-packages", commits: 19 }], location: "Amsterdam", bio: "Software Development Engineer", company: "@nebius" },
  { login: "theyoprst", name: "Slava Ezhkin", commits: 837, repos: [{ repo: "soperator", commits: 632 }, { repo: "nebius-solutions-library", commits: 205 }], location: "Berlin", company: "Nebius" },
  { login: "itechdima", name: "itechdima", commits: 647, repos: [{ repo: "soperator", commits: 408 }, { repo: "nebius-solutions-library", commits: 192 }, { repo: "ml-containers", commits: 27 }, { repo: "slurm-deb-packages", commits: 20 }] },
  { login: "rdjjke", name: "Mikhail Mokrushin", commits: 565, repos: [{ repo: "soperator", commits: 355 }, { repo: "nebius-solutions-library", commits: 175 }, { repo: "soperator-terraform", commits: 30 }, { repo: "ml-containers", commits: 5 }], location: "Amsterdam", company: "Nebius" },
  { login: "complynx", name: "Daniel", commits: 462, repos: [{ repo: "js-sdk", commits: 281 }, { repo: "pysdk", commits: 129 }, { repo: "api", commits: 19 }, { repo: "terraform-provider-nebius", commits: 18 }, { repo: "gosdk", commits: 15 }], location: "Amsterdam" },
  { login: "ChessProfessor", name: "Boris Serenkov", commits: 387, repos: [{ repo: "soperator", commits: 305 }, { repo: "nebius-solutions-library", commits: 55 }, { repo: "ml-containers", commits: 23 }, { repo: "slurm-deb-packages", commits: 4 }], location: "Amsterdam", company: "Nebius" },
  { login: "nebius-devtools", name: "Nebius Devtools Bot", commits: 141, repos: [{ repo: "api", commits: 111 }, { repo: "gosdk", commits: 22 }, { repo: "pysdk", commits: 5 }, { repo: "terraform-provider-nebius", commits: 3 }], company: "@nebius" },
  { login: "ali-sattari", name: "Ali Sattari", commits: 117, repos: [{ repo: "soperator", commits: 59 }, { repo: "nebius-solutions-library", commits: 54 }, { repo: "nfs-server", commits: 4 }], location: "Amsterdam", bio: "SRE", company: "Nebius" },
  { login: "bahmanzadeh", name: "Reza", commits: 101, repos: [{ repo: "nebius-ps-services", commits: 100 }, { repo: "ml-cookbook", commits: 1 }], location: "USA", bio: "AI/ML Engineering, Solutions Architecture, Cloud Infrastructure, AI/ML/HPC Infrastructure, Kubernetes, DevOps, MLOps, Automation, Networking, Observability" },
  { login: "roman-iurkov", name: "roman-iurkov", commits: 97, repos: [{ repo: "nebius-solutions-library", commits: 96 }, { repo: "ml-cookbook", commits: 1 }] },
  { login: "maratori", name: "Marat Reimers", commits: 88, repos: [{ repo: "gosdk", commits: 50 }, { repo: "api", commits: 38 }], location: "Netherlands", company: "Nebius" },
  { login: "valner", name: "valner", commits: 81, repos: [{ repo: "nebius-observability-agent-updater", commits: 65 }, { repo: "nebius-k8s-applications", commits: 16 }] },
  { login: "sujee", name: "Sujee Maniyam", commits: 78, repos: [{ repo: "token-factory-cookbook", commits: 78 }], location: "San Jose, CA, USA", bio: "contact: sujee@sujee.dev or via socials", company: "Nebius", twitter: "sujee_dev" },
  { login: "mosquito", name: "Mosquito", commits: 70, repos: [{ repo: "contree-cli", commits: 38 }, { repo: "contree-mcp", commits: 31 }, { repo: "contree-sdk", commits: 1 }], location: "Netherlands", company: "Nebius" },
  { login: "elijah-k-nebius", name: "elijah-k-nebius", commits: 66, repos: [{ repo: "nebius-solutions-library", commits: 63 }, { repo: "nebius-k8s-applications", commits: 3 }] },
  { login: "malibora", name: "malibora", commits: 56, repos: [{ repo: "nebius-solutions-library", commits: 56 }] },
  { login: "SalikovAlex", name: "Alexander", commits: 56, repos: [{ repo: "nebius-k8s-applications", commits: 56 }], location: "UK", company: "@nebius" },
  { login: "faucct", name: "Nikita Sokolov", commits: 50, repos: [{ repo: "soperator", commits: 48 }, { repo: "nebius-solutions-library", commits: 2 }] },
  { login: "cyril-k", name: "Cyril K", commits: 50, repos: [{ repo: "ml-cookbook", commits: 39 }, { repo: "nebius-solutions-library", commits: 11 }], bio: "AI Specialist Solutions Architect @nebius", company: "@nebius" },
  { login: "d3vil-st", name: "Ilya Kargapolov", commits: 41, repos: [{ repo: "nebius-solutions-library", commits: 32 }, { repo: "nebius-k8s-applications", commits: 9 }], location: "Belgrade" },
  { login: "aaroniscode", name: "Aaron Miller", commits: 37, repos: [{ repo: "nebius-solutions-library", commits: 33 }, { repo: "soperator", commits: 2 }, { repo: "nebius-k8s-applications", commits: 1 }, { repo: "ml-cookbook", commits: 1 }], location: "Phoenix, AZ", bio: "Principal Solutions Architect at @nebius", company: "@nebius" },
  { login: "alex000kim", name: "Alex Kim", commits: 36, repos: [{ repo: "nebius-solutions-library", commits: 29 }, { repo: "ml-cookbook", commits: 7 }], location: "Montreal, QC", bio: "Dad👧🏻👦🏻 | ML Engineer | Technical Instructor | Consultant | Community Builder" },
  { login: "fxrlv", name: "Alexander Frolov", commits: 35, repos: [{ repo: "nebius-k8s-applications", commits: 34 }, { repo: "observability", commits: 1 }], location: "Amsterdam", company: "@nebius" },
  { login: "walkerus", name: "Ruslan Isamukhametov", commits: 35, repos: [{ repo: "packer-plugin-nebius", commits: 35 }], location: "Amsterdam", company: "Nebius" },
  { login: "keyvaann", name: "Keyvan", commits: 29, repos: [{ repo: "nebius-solutions-library", commits: 28 }, { repo: "nebius-k8s-applications", commits: 1 }], location: "Netherlands" },
  { login: "delphikettle", name: "Andrei Andriushchenko", commits: 25, repos: [{ repo: "contree-sdk", commits: 25 }], location: "Haarlem, Netherlands", company: "Nebius" },
  { login: "Maurits-de-Groot", name: "Maurits de Groot", commits: 24, repos: [{ repo: "ml-cookbook", commits: 13 }, { repo: "nebius-solutions-library", commits: 11 }] },
  { login: "dglinyanov", name: "Glinyanov Dmitry", commits: 19, repos: [{ repo: "mcp-server", commits: 19 }], location: "Spain, Valencia" },
  { login: "southfreebird", name: "Sergei Skvortsov", commits: 18, repos: [{ repo: "kvax", commits: 18 }], location: "London, UK", company: "Nebius" },
  { login: "negrovalar", name: "negrovalar", commits: 17, repos: [{ repo: "nebius-solutions-library", commits: 17 }] },
  { login: "jadnov", name: "jadnov", commits: 16, repos: [{ repo: "nebius-solutions-library", commits: 11 }, { repo: "ml-cookbook", commits: 5 }] },
  { login: "webconn", name: "Maslov Nikita", commits: 15, repos: [{ repo: "soperator", commits: 9 }, { repo: "nebius-solutions-library", commits: 6 }], company: "@nebius" },
  { login: "guanruhuang-nebius", name: "guanruhuang-nebius", commits: 14, repos: [{ repo: "nebius-solutions-library", commits: 14 }] },
  { login: "rene-tech", name: "rene-tech", commits: 14, repos: [{ repo: "nebius-solutions-library", commits: 14 }] },
  { login: "secrettoad", name: "secrettoad", commits: 13, repos: [{ repo: "nebius-solutions-library", commits: 13 }] },
  { login: "panukosk", name: "panukosk", commits: 11, repos: [{ repo: "nebius-solutions-library", commits: 11 }] },
  { login: "ilyash89", name: "Ilya Shargorodskiy", commits: 11, repos: [{ repo: "api", commits: 11 }], location: "Amsterdam, the Netherlands", company: "Nebius" },
  { login: "orloffv", name: "Vitaly Orlov", commits: 11, repos: [{ repo: "observability", commits: 8 }, { repo: "nebius-observability-agent-updater", commits: 3 }], location: "Amsterdam", company: "Nebius" },
  { login: "abrekhov", name: "Anton Brekhov", commits: 10, repos: [{ repo: "csa-workshops", commits: 10 }], bio: "Nanoservices" },
  { login: "mateusclira-nv", name: "Mateus Lira", commits: 10, repos: [{ repo: "soperator", commits: 10 }], company: "@NVIDIA" },
  { login: "bogdanov1609", name: "spooner", commits: 10, repos: [{ repo: "nebius-observability-agent-updater", commits: 7 }, { repo: "nebius-k8s-applications", commits: 3 }], location: "Amsterdam", company: "Netherlands" },
  { login: "iglunchadze", name: "Irakliy Glunchadze", commits: 9, repos: [{ repo: "nebius-solutions-library", commits: 5 }, { repo: "soperator", commits: 4 }] },
  { login: "pbutler", name: "Patrick Butler", commits: 9, repos: [{ repo: "nebius-solutions-library", commits: 9 }], location: "Washington, DC", bio: "AI/ML Specialist SA at @nebius", company: "Nebius" },
  { login: "idanb1", name: "idanb1", commits: 9, repos: [{ repo: "nebius-solutions-library", commits: 9 }] },
  { login: "Arindam200", name: "Arindam Majumder ", commits: 9, repos: [{ repo: "token-factory-cookbook", commits: 9 }], location: "India", bio: "Building @Studio1HQ", company: "Studio1HQ.com", twitter: "Arindam_1729" },
  { login: "mcheshkov", name: "Mikhail Cheshkov", commits: 8, repos: [{ repo: "soperator", commits: 8 }] },
  { login: "iamrajiv", name: "Rajiv Singh", commits: 8, repos: [{ repo: "soperator", commits: 8 }], location: "Bengaluru, India", bio: "SDE JL3 @Maersk-Global | Ex Lummo, redBus, Economize | GSoC Mentor '23 '24 @jenkinsci | GSoC '22 @keptn | LFX  '21 @moja-global | GSoD '20 @grpc-ecosystem", twitter: "therajiv" },
  { login: "nevgeny", name: "Evgeny Martyn", commits: 8, repos: [{ repo: "soperator", commits: 4 }, { repo: "nebius-k8s-applications", commits: 4 }], location: "Amsterdam, Netherlands" },
  { login: "mnrozhkov", name: "Mikhail Rozhkov", commits: 8, repos: [{ repo: "serverless-ai-cookbook", commits: 8 }], bio: "AI & Machine Learning, Robotics, Product Management", company: "Machine Learning REPA Community", twitter: "mnrozhkov" },
  { login: "vano468", name: "Ivan Kornilov", commits: 7, repos: [{ repo: "mcp-server", commits: 4 }, { repo: "pysdk", commits: 2 }, { repo: "terraform-provider-nebius", commits: 1 }] },
  { login: "patrick-239", name: "Aleksandr Patrushev", commits: 7, repos: [{ repo: "serverless-ai-cookbook", commits: 7 }] },
  { login: "Astrodevil", name: "Mr. Ånand", commits: 6, repos: [{ repo: "token-factory-cookbook", commits: 6 }], location: "Jezero Crater, Mars", bio: "Learning & Writing Codes.", company: "Studio1HQ", twitter: "Astrodevil_" },
  { login: "briskly", name: "Nikita Vdovushkin", commits: 5, repos: [{ repo: "nccl-topology", commits: 5 }], company: "BalalaikaCr3w, CTFZone, offzone, bi.zone" },
  { login: "step-security-bot", name: "StepSecurity Bot", commits: 5, repos: [{ repo: "soperator", commits: 2 }, { repo: "soperator-terraform", commits: 2 }, { repo: "slurm-deb-packages", commits: 1 }], bio: "@step-security bot account for creating PRs. Fix GitHub Actions security issues using https://app.stepsecurity.io/securerepo", company: "StepSecurity" },
  { login: "yozel", name: "Yasin Özel", commits: 5, repos: [{ repo: "soperator", commits: 5 }], location: "Amsterdam, NL", company: "@nebius" },
  { login: "CrackedPoly", name: "Jian Luo", commits: 5, repos: [{ repo: "soperator", commits: 5 }], location: "Earth" },
  { login: "dasbatta", name: "Das Batta", commits: 5, repos: [{ repo: "nebius-solutions-library", commits: 4 }, { repo: "soperator", commits: 1 }] },
  { login: "shoguevara", name: "ShoGuevara", commits: 5, repos: [{ repo: "nebius-solutions-library", commits: 5 }] },
  { login: "afonsonebius", name: "afonsonebius", commits: 5, repos: [{ repo: "nebius-solutions-library", commits: 5 }] },
  { login: "alena-linki", name: "Alyona Vorobyova", commits: 5, repos: [{ repo: "nebius-solutions-library", commits: 5 }], bio: "Technical writer" },
  { login: "andriishestakov", name: "andriishestakov", commits: 4, repos: [{ repo: "soperator", commits: 4 }] },
  { login: "yarikoptic", name: "Yaroslav Halchenko", commits: 4, repos: [{ repo: "soperator", commits: 4 }], location: "Planet Earth", bio: "Cheers!", company: "Dartmouth College, @dandi, @Debian, @DataLad, @neurodebian, @PyMVPA, @fail2ban" },
  { login: "andrei-pokhila", name: "Andrei Pokhila", commits: 4, repos: [{ repo: "soperator", commits: 3 }, { repo: "nebius-solutions-library", commits: 1 }] },
  { login: "aaronbfagan", name: "aaronbfagan", commits: 4, repos: [{ repo: "nebius-solutions-library", commits: 4 }] },
  { login: "timothy-le7", name: "Timothy Le", commits: 4, repos: [{ repo: "nebius-solutions-library", commits: 4 }] },
  { login: "mvnebius", name: "mvnebius", commits: 4, repos: [{ repo: "nebius-solutions-library", commits: 4 }] },
  { login: "realvz", name: "Re Alvarez Parmar", commits: 4, repos: [{ repo: "nebius-solutions-library", commits: 3 }, { repo: "serverless-ai-cookbook", commits: 1 }], location: "Seattle", bio: "Fueled by caffeine and scrolling stdout.", company: "Nebius" },
  { login: "shivaycb", name: "Shivay ", commits: 4, repos: [{ repo: "token-factory-cookbook", commits: 4 }], location: "Bangalore", bio: "Shivay" },
  { login: "Pavel-Karpenko", name: "Pavel Karpenko", commits: 3, repos: [{ repo: "csa-workshops", commits: 3 }] },
  { login: "sena1482", name: "sena1482", commits: 3, repos: [{ repo: "soperator", commits: 3 }] },
  { login: "MeenaAlfons", name: "Meena Alfons", commits: 3, repos: [{ repo: "soperator", commits: 2 }, { repo: "nebius-solutions-library", commits: 1 }], location: "Amsterdam, Netherlands", bio: "Senior Software Engineer" },
  { login: "zandreika", name: "Andrei Zenkov", commits: 3, repos: [{ repo: "js-sdk", commits: 2 }, { repo: "gosdk", commits: 1 }] },
  { login: "eshlykov", name: "Evgenii", commits: 3, repos: [{ repo: "packer-plugin-nebius", commits: 3 }], location: "Berlin, Germany" },
  { login: "devolya", name: "Olga Loginova", commits: 2, repos: [{ repo: "slurm-deb-packages", commits: 2 }] },
  { login: "karaimin", name: "Aleydin Karaimin", commits: 2, repos: [{ repo: "soperator", commits: 2 }], location: "Sofia", company: "@SAP " },
  { login: "andreineustroev", name: "Андрей", commits: 2, repos: [{ repo: "soperator", commits: 2 }], location: "Russia, Yekaterinburg", company: "Naumen" },
  { login: "ivaravko", name: "Ihar Varauka", commits: 2, repos: [{ repo: "soperator", commits: 2 }], location: "Berlin", company: "@affinidi" },
  { login: "HoomanRamezani", name: "Hooman Ramezani", commits: 2, repos: [{ repo: "nebius-solutions-library", commits: 2 }], location: "Toronto", bio: "ML Specialist Solution Architect @ Nebius", company: "Nebius" },
  { login: "JathavanSriramNVIDIA", name: "Jathavan Sriram (NVIDIA)", commits: 2, repos: [{ repo: "nebius-solutions-library", commits: 2 }] },
  { login: "dorukozturk", name: "Doruk Ozturk", commits: 2, repos: [{ repo: "nebius-solutions-library", commits: 2 }], location: "New York City", company: "Nebius" },
  { login: "sdwbgn", name: "Vasilii Bulatov", commits: 2, repos: [{ repo: "nebius-connect", commits: 2 }], location: "Amsterdam, Netherlands" },
  { login: "ApInvent", name: "Evgeny", commits: 2, repos: [{ repo: "nebius-k8s-applications", commits: 2 }], location: "Amsterdam, Netherlands" },
  { login: "fshchudlo", name: "Fedor Shchudlo", commits: 2, repos: [{ repo: "nebius-k8s-applications", commits: 2 }], location: "Amsterdam, Netherlands", company: "Nebius" },
  { login: "Aktsvigun", name: "Akim Tsvigun", commits: 2, repos: [{ repo: "langchain-nebius", commits: 2 }], location: "Amsterdam, Netherlands", company: "Nebius AI" },
  { login: "ah-nebius", name: "ah-nebius", commits: 2, repos: [{ repo: "langchain-nebius", commits: 2 }] },
  { login: "lakshyaag-tavily", name: "Lakshya Agarwal", commits: 2, repos: [{ repo: "token-factory-cookbook", commits: 2 }], location: "Toronto, ON", company: "Tavily", twitter: "lakshyaag" },
  { login: "bbelky", name: "Vladimir Porokhov", commits: 2, repos: [{ repo: "observability", commits: 2 }], location: "Cyprus", bio: "Product Manager, Serverless technology enthusiast", company: "Limassol" },
  { login: "nar3k", name: "nar3k", commits: 1, repos: [{ repo: "csa-workshops", commits: 1 }], location: "Armenia" },
  { login: "apten-fors", name: "Aleksandr Zhitnikov", commits: 1, repos: [{ repo: "soperator", commits: 1 }], location: "Cyprus", company: "@G-Core " },
  { login: "dvolk", name: "Denis Volk", commits: 1, repos: [{ repo: "soperator", commits: 1 }], location: "Oxford" },
  { login: "janekmichalik", name: "Jan Michalik", commits: 1, repos: [{ repo: "soperator", commits: 1 }], location: "Gdynia", bio: "Kubernetes DevOps Engineer — Global k0rdent-ai at Mirantis  CKAD | CKA | CKS", company: "Mirantis" },
  { login: "tomkukral", name: "Tomáš Kukrál", commits: 1, repos: [{ repo: "soperator", commits: 1 }], location: "Kluky, Czech Republic", company: "Second Foundation" },
  { login: "angelbejarano", name: "angelbejarano", commits: 1, repos: [{ repo: "soperator", commits: 1 }] },
  { login: "dnugmanov", name: "dnugmanov", commits: 1, repos: [{ repo: "soperator", commits: 1 }] },
  { login: "ozerovandrei", name: "Andrei Ozerov", commits: 1, repos: [{ repo: "nebius-solutions-library", commits: 1 }], location: "Amsterdam, the Netherlands", bio: "Software Engineer / SRE", company: "Nebius" },
  { login: "brianlechthaler", name: "Brian Lechthaler", commits: 1, repos: [{ repo: "nebius-solutions-library", commits: 1 }], location: "San Francisco, CA", bio: "🏳️‍⚧️🏳️‍🌈 Proudly non-binary AI/HPC focused engineer who enjoys building all sorts of things.  Founding Solutions Architect @sfcompute", company: "@sfcompute", twitter: "brianlechthaler" },
  { login: "PhilipMantrov", name: "Philip Mantrov", commits: 1, repos: [{ repo: "nebius-solutions-library", commits: 1 }] },
  { login: "iofits", name: "iofits", commits: 1, repos: [{ repo: "nebius-solutions-library", commits: 1 }] },
  { login: "mohalisad", name: "MohammadAli Sadraei", commits: 1, repos: [{ repo: "pysdk", commits: 1 }] },
  { login: "TimSchneider42", name: "Tim Schneider", commits: 1, repos: [{ repo: "kvax", commits: 1 }] },
  { login: "evanYDL", name: "Evan Rimer", commits: 1, repos: [{ repo: "token-factory-cookbook", commits: 1 }] },
  { login: "shivaylamba", name: "Shivay Lamba", commits: 1, repos: [{ repo: "token-factory-cookbook", commits: 1 }], location: "New Delhi, India", bio: "GSoC Org Admin & Mentor 2024/25/26 @jenkinsci @kubeflow ||  @GSoC Mentor 2021 @tensorflow ||  GSoC Mentor 2020 @jenkinsci @cncf", twitter: "howdevelop" },
  { login: "demianarc", name: "dylan", commits: 1, repos: [{ repo: "token-factory-cookbook", commits: 1 }], bio: "just having fun" },
  { login: "DmitrySafonov", name: "DmitrySafonov", commits: 1, repos: [{ repo: "observability", commits: 1 }], location: "Portugal", company: "Nebius" },
  { login: "dtyo-nebius", name: "dtyo-nebius", commits: 1, repos: [{ repo: "observability", commits: 1 }] },
  { login: "erossy", name: "erossy", commits: 1, repos: [{ repo: "observability", commits: 1 }] },
  { login: "dashabalashova", name: "Dasha Balashova", commits: 1, repos: [{ repo: "nebius-ps-services", commits: 1 }], location: "Amsterdam" },
  { login: "aleksandr-dzhumurat", name: "aleksandr-dzhumurat", commits: 1, repos: [{ repo: "serverless-ai-cookbook", commits: 1 }] },
  { login: "GlebBerjoskin", name: "GlebBerjoskin", commits: 1, repos: [{ repo: "serverless-ai-cookbook", commits: 1 }] },
];
