// Showcase projects scraped from the two hackathon galleries Colin pasted in:
//   - Nebius.Build SF Hackathon (March 2026)
//   - JetBrains × OpenAI / Codex Hackathon (April 2026)
//
// Each entry's `description` is a short paraphrase of the project's own README /
// gallery blurb. `productFocus` flags which Nebius (or partner) products the
// project uses — projects with no Nebius / Tavily / Token Factory / AI Cloud /
// OpenClaw / Soperator mention get tagged `"other"` so we can filter or prune.

export type ProjectAuthorRole = "builder" | "ambassador" | "advocate";

export type ProjectAuthor = {
  name: string;
  handle: string;
  role: ProjectAuthorRole;
};

export type ProjectAward = {
  label: string;
  sponsor?: string;
};

export type Project = {
  slug: string;
  title: string;
  lede: string;
  description: string;
  cover: string;
  productFocus: string[];
  technologies: string[];
  authors: ProjectAuthor[];
  eventId?: string;
  eventTitle?: string;
  awards?: ProjectAward[];
  githubUrl?: string;
  demoUrl?: string;
  videoUrl?: string;
  shippedAt: string;
};

// -- constants ---------------------------------------------------------------

const NB_HACK = "Nebius.Build SF Hackathon — March 2026";
const JB_HACK = "JetBrains × OpenAI Codex Hackathon — April 2026";
const NB_DATE = "2026-03-16T00:00:00Z";
const JB_DATE = "2026-04-19T00:00:00Z";

const COVERS = [
  "from-lime-300 via-lime-200 to-navy-700",
  "from-navy-800 via-navy-700 to-lime/40",
  "from-lime-400 via-lime-200 to-navy-500",
  "from-navy-700 via-navy-600 to-lime/40",
  "from-lime-300 via-lime-400 to-navy-700",
  "from-lime-200 via-lime-300 to-lime-400",
  "from-navy-700 via-navy-500 to-lime/40",
  "from-lime-300 via-navy-500 to-navy-700",
  "from-navy-600 via-lime-300 to-lime-200",
  "from-lime-400 via-navy-600 to-navy-800",
];
const c = (i: number) => COVERS[i % COVERS.length];

// -- projects ----------------------------------------------------------------

export const projects: Project[] = [
  // ===== Nebius.Build SF — Winners + Finalists =====
  {
    slug: "injester",
    title: "Injester",
    lede: "Drop any URL in; get back an AI-agent-actionable version of the page plus a side-by-side benchmark showing an agent go from 2/5 to 5/5 on the same task.",
    description:
      "Tavily Extract strips HTML noise. A Nebius Token Factory model (Llama 3.1 70B / Qwen) restructures the content. A self-improvement loop iterates on the restructuring prompt for three rounds. FastAPI + React.",
    cover: c(0),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Python", "FastAPI", "React", "Tavily", "Llama 3.1 70B", "Qwen"],
    authors: [
      { name: "Alex Shirazi", handle: "slowpoison", role: "builder" },
      { name: "Vishal Verma", handle: "BenjaminBear", role: "builder" },
      { name: "Benjamin Shyong", handle: "benshyong", role: "builder" },
    ],
    eventTitle: NB_HACK,
    awards: [{ label: "Winner", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/InjesterLol/Main",
    shippedAt: NB_DATE,
  },
  {
    slug: "runrobot",
    title: "runrobot",
    lede: "First human-preference datasets for robot policies in simulation. Nebius GPUs run head-to-head matchups; ELO + anti-cheat measures rank which policies actually work.",
    description:
      "Researchers package a policy, validate locally, run the same artifact in browser / sim / on hardware, and publish to RunRobot Cloud. The hackathon submission also wired up a working leaderboard.",
    cover: c(1),
    productFocus: ["aicloud"],
    technologies: ["TypeScript", "JavaScript", "Policy YAML", "Nebius GPUs"],
    authors: [
      { name: "Chase Brignac", handle: "chasebrignac", role: "builder" },
      { name: "Zainab Bokhari", handle: "thatroboticsgrl", role: "builder" },
    ],
    eventTitle: NB_HACK,
    awards: [{ label: "Runner-up", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/runrobotics/runrobot",
    shippedAt: NB_DATE,
  },
  {
    slug: "robostore",
    title: "RoboStore",
    lede: "Self-expanding robot agent: detects its own hardware gaps, searches a real parts catalog, auto-generates integration skills, installs them, and retries the task.",
    description:
      "OpenClaw orchestrator coordinates three agents in parallel — SCOUT (Qwen2-VL-72B vision), PLANNER (Qwen3-235B reasoning), SAFETY (MuJoCo rollouts). 20+ real hardware modules pulled live from Adafruit's API.",
    cover: c(2),
    productFocus: ["openclaw", "tokenfactory", "aicloud"],
    technologies: ["Python", "OpenClaw", "Qwen2-VL-72B", "Qwen3-235B", "Token Factory", "ROS2", "MuJoCo"],
    authors: [
      { name: "Stephen Lantin", handle: "astrobiopunk", role: "builder" },
      { name: "Gary Holmgren", handle: "garyholmgren", role: "builder" },
      { name: "Joshua Iokua Albano", handle: "jiokua", role: "builder" },
    ],
    eventTitle: NB_HACK,
    awards: [{ label: "3rd Place", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/joshuaiokua/nebius-hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "k1-walking-talking",
    title: "K1 Walking & Talking",
    lede: "Voice-controlled Booster K1 humanoid that understands its surroundings — location, mapping, and follows-around behaviors driven by natural speech.",
    description:
      "Real-time voice loop on Gemini Live API drives the K1. YOLOv8 handles object detection on stereo cameras; ROS2 topics carry frames; face recognition tracks who's in the room.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["Python", "Gemini Live API", "YOLOv8", "ROS2", "Booster K1"],
    authors: [
      { name: "Armin Foroughi", handle: "arminforoughi", role: "builder" },
      { name: "Sharon Xu", handle: "sharx", role: "builder" },
    ],
    eventTitle: NB_HACK,
    awards: [{ label: "Finalist", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/arminforoughi/nebius_k1",
    demoUrl: "https://www.youtube.com/shorts/p58thp6nE-A",
    shippedAt: NB_DATE,
  },
  {
    slug: "topology",
    title: "TOPOLOGY",
    lede: "Evolutionary agent-org discovery — 10 LLM-agent teams with randomly generated org genomes compete; the weakest dissolve, the strongest mutate over 5 generations.",
    description:
      "Three Nebius model tiers: Llama 3.1 8B-fast for agent execution and role generation, Llama 3.3 70B-fast for evaluation, DeepSeek-R1 for the final synthesis. Real-time Canvas2D viz of the topologies.",
    cover: c(4),
    productFocus: ["tokenfactory"],
    technologies: ["Python", "WebSockets", "Canvas2D", "Llama 3.1 8B", "Llama 3.3 70B", "DeepSeek-R1"],
    authors: [{ name: "Nigel Robinson", handle: "nxrobins", role: "builder" }],
    eventTitle: NB_HACK,
    awards: [{ label: "Finalist", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/nxrobins/topology",
    shippedAt: NB_DATE,
  },
  {
    slug: "asha",
    title: "Asha",
    lede: "WhatsApp-native AI assistant for small home-based food businesses. Takes orders in natural language including Hinglish, remembers preferences, sends daily summaries.",
    description:
      "Customers text Ash directly on WhatsApp; owners chat with Ash to set up the business. Twilio routes messages, multi-agent system on Nebius Serverless handles intent + memory + order coordination, Supabase backs the realtime dashboard.",
    cover: c(5),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["TypeScript", "Python", "Twilio", "WhatsApp Business API", "Nebius Serverless", "Supabase"],
    authors: [
      { name: "Geoffrey Ju", handle: "geoffrey-ju", role: "builder" },
      { name: "Ranya Belmaachi", handle: "ranyabel", role: "builder" },
      { name: "Mohammed Misran", handle: "misran3", role: "builder" },
    ],
    eventTitle: NB_HACK,
    awards: [{ label: "Finalist", sponsor: "Nebius.Build SF" }],
    githubUrl: "https://github.com/misran3/asha",
    demoUrl: "https://drive.google.com/file/d/1RjiQio_4Iy6TRSmWpwu5q8mLSmsm8VXk/view?usp=sharing",
    shippedAt: NB_DATE,
  },

  // ===== Nebius.Build SF — Other Projects (Nebius/Tavily-using) =====
  {
    slug: "cdmo-bot",
    title: "CDMO.BOT / KETABALM",
    lede: "Autonomous robotic compounding system that turns idle pharma cleanroom capacity into a distributed network for personalized therapeutics.",
    description:
      "Biometric sensors feed a Nebius Token Factory Llama 3.1 70B dosing agent. An orchestrator dispatches tasks to a simulated Unitree G1 in Isaac Sim. Every cycle writes a timestamped audit event with inference cost attribution.",
    cover: c(6),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["React", "FastAPI", "Isaac Sim", "MuJoCo", "Token Factory", "Llama 3.1 70B", "Nebius AI Cloud L40S"],
    authors: [{ name: "Lorenzo Carver", handle: "TRIPBalm", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/FludAI/cdmobot-backend",
    shippedAt: NB_DATE,
  },
  {
    slug: "dronomy-flight",
    title: "dronomy.io — Autonomous Flight",
    lede: "Dockerized autonomous drone simulator with a dual-mode RL correction agent — toggle between a sim Q-learning policy and a live LLM policy backed by Nebius.",
    description:
      "24-ray LiDAR SLAM, EKF state estimation, A* planning, DWA local planning, and an 8-state flight FSM. The LLM mode runs Llama 3.1 8B on H100s via Nebius Token Factory at ~700ms latency.",
    cover: c(7),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["Python", "FastAPI", "React", "Vite", "Llama 3.1 8B", "Token Factory", "WebSocket"],
    authors: [{ name: "Suvasis Mukherjee", handle: "suvasis", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/dronomyio/Hackathon_Autonomous_flight.git",
    shippedAt: NB_DATE,
  },
  {
    slug: "physprobe",
    title: "PhysProbe",
    lede: "Self-improving robot skill framework that benchmarks 8 world models on Nebius Token Factory for physics prediction — Qwen3-235B wins at 90% accuracy in 696ms.",
    description:
      "When models agree, the robot skips probing. When they disagree, one gentle 5N touch gives 94% certainty. A swarm of agents (Diagnostician → Inventor → Critic) invents new skills on failure. +34pp skill delta across 750 trials.",
    cover: c(8),
    productFocus: ["tokenfactory"],
    technologies: ["Python", "Qwen3-235B", "Token Factory"],
    authors: [{ name: "Sidra Miconi", handle: "Sidra", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Sidra/physprobe-nebius",
    shippedAt: NB_DATE,
  },
  {
    slug: "claw2max",
    title: "Claw2Max — MechDog skill",
    lede: "An OpenClaw skill and simulator for the Hiwonder MechDog robot dog.",
    description: "Drop-in skill that lets OpenClaw agents drive the MechDog through its native control interface.",
    cover: c(9),
    productFocus: ["openclaw"],
    technologies: ["Python", "OpenClaw", "Hiwonder MechDog"],
    authors: [{ name: "Max Maximilien", handle: "maximilien", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Maximilien-ai/mechdog-skill",
    shippedAt: NB_DATE,
  },
  {
    slug: "clawdit",
    title: "Clawdit",
    lede: "Auto-discovers your OpenClaw agent's linked Google account and tricks it into sending malicious emails / calendar invites to itself — then watches whether the agent follows the hidden instructions.",
    description:
      "Llama 3.3 70B on Nebius Token Factory generates and evaluates attack variants; Tavily provides real-time threat intel. Baseline checks for prompt injection, data leakage, unauthorized actions, and access control.",
    cover: c(0),
    productFocus: ["openclaw", "tokenfactory", "tavily"],
    technologies: ["Python", "OpenClaw", "Llama 3.3 70B", "Token Factory", "Tavily"],
    authors: [{ name: "Yuwen Wu", handle: "jww", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/wuyuwenj/clawdit.git",
    shippedAt: NB_DATE,
  },
  {
    slug: "cre808ive-trade-twins",
    title: "MMCP Trade Twins",
    lede: "Constitutional multi-agent system that agentically builds digital-twin knowledge bases for 24+ licensed skilled trades simultaneously, governed by one constitutional layer.",
    description:
      "One command triggers 24 specialized agents — one per trade. Nebius Token Factory runs Mixtral-8x7B inference; Tavily pulls live authoritative trade codes; Toloka human validators gate every output before it becomes a provenance-hashed marble.",
    cover: c(1),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Python", "Mixtral-8x7B", "Token Factory", "Tavily", "Toloka", "Scroll Blockchain"],
    authors: [{ name: "Daniel Kaneshiro", handle: "Cre808ive", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/ChainMailGlobal/Nebius.Build",
    shippedAt: NB_DATE,
  },
  {
    slug: "framewise",
    title: "Framewise",
    lede: "Cuts robot perception costs 80–90% by never sending the same scene twice — pixel + semantic change detection gates inference.",
    description:
      "Only the changed region gets sent, only when something moved. A fast draft model (Gemma-27B) answers first; if uncertain, it escalates to Qwen-72B. RAG, reranking, and Tavily round out the context layer.",
    cover: c(2),
    productFocus: ["tavily"],
    technologies: ["Python", "Gemma-27B", "Qwen-72B", "Tavily", "RAG"],
    authors: [{ name: "Aishwarya Gune", handle: "aishwaryagune", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/agg111/framewise",
    shippedAt: NB_DATE,
  },
  {
    slug: "chai",
    title: "CHAI — Companion Humanoid AI",
    lede: "Real-time companion system for the Unitree G1: detects approaching humans, greets them, and autonomously clears obstacles to act as a guide for visually impaired users.",
    description:
      "Nebius AI Studio's Qwen2.5-VL-72B handles vision; Llama-3.3-70B handles decision-making. Runs in MuJoCo simulation against G1 hardware traces.",
    cover: c(3),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["Python", "Qwen2.5-VL-72B", "Llama-3.3-70B", "MuJoCo", "Unitree G1"],
    authors: [
      { name: "Vatsal Bajaj", handle: "vb99", role: "builder" },
      { name: "Jake Kang", handle: "kangjake", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/galileo-ml/nebius-hack",
    shippedAt: NB_DATE,
  },
  {
    slug: "switchcost",
    title: "SwitchCost",
    lede: "AI inference migration engine — safely move from GPT-4 / Claude / Gemini to open-source models on Nebius Token Factory while maintaining quality parity.",
    description:
      "Decomposes a task into typed subtasks, replays each against every available Nebius and OpenRouter model, scores quality via LLM-as-judge, and recommends the cheapest model per subtask type that maintains >80% quality.",
    cover: c(4),
    productFocus: ["tokenfactory"],
    technologies: ["Python", "Token Factory", "OpenRouter", "LLM-as-judge"],
    authors: [{ name: "Ayush Ojha", handle: "ayushojha", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Ayush10/switchcost",
    shippedAt: NB_DATE,
  },
  {
    slug: "agentcommerce",
    title: "AgentCommerce",
    lede: "Two AI agents — a Buyer and a Merchant on different providers — negotiate purchases end-to-end with zero humans, in under 60 seconds.",
    description:
      "Buyer on Nebius AI Studio (MiniMax-M2.1), Merchant on OpenRouter (MiniMax-M2). Tavily Search pulls live market prices. ISO 18013-5 mdoc credentials cryptographically verify both parties before money moves.",
    cover: c(5),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Python", "React", "MiniMax-M2.1", "Tavily Search", "ISO 18013-5 mdoc", "WebSocket"],
    authors: [{ name: "Diego Zuluaga", handle: "DiegoZ", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/dzuluaga/agentcommerce",
    shippedAt: NB_DATE,
  },
  {
    slug: "arm-pilot",
    title: "arm-pilot",
    lede: "Robot receives a job command; a Nebius-powered LLM searches the internet for the right task and retrieves motion data, then deploys it directly to the arm.",
    description:
      "Demo runs pick-and-press on a humanoid arm. Tavily handles grounding search; the loop is closed end-to-end so a single command kicks off discovery → motion retrieval → execution.",
    cover: c(6),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Python", "Token Factory", "Tavily"],
    authors: [
      { name: "Sota Miyajima", handle: "Sota", role: "builder" },
      { name: "Munenori Saito", handle: "saito", role: "builder" },
      { name: "Kouta Ueda", handle: "kota", role: "builder" },
      { name: "Kush Ise", handle: "KUSH2704", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Sota-sota/nebius-build-sf-2026/tree/kush",
    shippedAt: NB_DATE,
  },
  {
    slug: "autorobots",
    title: "AutoRobots",
    lede: "Autonomous AI scientist that teaches simulated robots to move — no human reward engineering.",
    description:
      "The LLM agent iterates on reward functions, trains RL policies, evaluates results, and accumulates improvements. All training runs on Nebius infrastructure.",
    cover: c(7),
    productFocus: ["aicloud"],
    technologies: ["Python", "Reinforcement Learning", "Nebius Cloud"],
    authors: [
      { name: "Warner Wu", handle: "warner", role: "builder" },
      { name: "Astral Labs", handle: "Astral", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/anjan04/nebiushack",
    shippedAt: NB_DATE,
  },
  {
    slug: "autoevolve",
    title: "AutoEvolve",
    lede: "Cloud-side task planner on Nebius Token Factory (Qwen 2.5) decomposes \"pick up the cup\" into fine-grained manipulation steps; a fine-tuned GR00T N1.6-3B turns each step into joint actions.",
    description:
      "VLM-driven continuous joint actions across reach-and-grasp, object handoff, and basic manipulation. Vision → reasoning → physical action pipeline.",
    cover: c(8),
    productFocus: ["tokenfactory"],
    technologies: ["Python", "Qwen 2.5", "Token Factory", "GR00T N1.6-3B"],
    authors: [
      { name: "Miaosen Zhou", handle: "then", role: "builder" },
      { name: "Lily Su", handle: "lilyxsu", role: "builder" },
      { name: "Long Haitao", handle: "takeiteasydragon", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/zhoumiaosen/AutoEvolve",
    shippedAt: NB_DATE,
  },
  {
    slug: "voiceclaw",
    title: "voiceClaw",
    lede: "Connect open-source ESP32 voice hardware (Xiaozhi) to OpenClaw Agent Gateway — plug in, speak, get an AI agent response.",
    description:
      "Bridges OpenClaw Agent Gateway with Xiaozhi ESP32 hardware via an LLM Passthrough architecture. Lightweight server implementations in Python, Go, and Swift.",
    cover: c(9),
    productFocus: ["openclaw"],
    technologies: ["Python", "Go", "Swift", "OpenClaw Agent Gateway", "ESP32"],
    authors: [{ name: "Zhuang Hua", handle: "aadebuger", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/aadebuger/voiceclaw-go",
    demoUrl: "https://youtube.com/shorts/0fqLpK6F_mI",
    shippedAt: NB_DATE,
  },
  {
    slug: "controlled-friction",
    title: "Controlled Friction",
    lede: "Intentional pauses and validation steps in the deployment pipeline, powered by Tavily Search in Nebius Token Factory.",
    description:
      "Layers of security, privacy, and content validation block malicious sources, prompt injection, and PII leakage during deploys. \"Protective\" friction as a braking system against rapid changes that cause production incidents.",
    cover: c(0),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Token Factory", "Tavily Search"],
    authors: [{ name: "Irina Poslavsky", handle: "msirina", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/kotrie/deployment-validation.yml",
    shippedAt: NB_DATE,
  },
  {
    slug: "grocery-stocksense",
    title: "Grocery StockSense",
    lede: "Photo your fridge or pantry; Qwen2.5-VL-72B on Nebius Cloud identifies food items with quantities and tells you what's missing from your pantry staples.",
    description:
      "Web dashboard, Telegram bot, or robot-camera capture. Cross-references detected items against a curated essentials list. Also simulated a robot opening a fridge door in MJ Lab Studio.",
    cover: c(1),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["Python", "Qwen2.5-VL-72B", "Nebius Cloud", "MuJoCo"],
    authors: [
      { name: "Rafael Maranon", handle: "rafamara", role: "builder" },
      { name: "Mansi Mane", handle: "mansimane", role: "builder" },
      { name: "Nathan Moos", handle: "moosnat", role: "builder" },
      { name: "Daksh Kumar", handle: "dkumar", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/mansimane/nebius-hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "nerdtres",
    title: "Nerdtres — NebulaPriceAgent",
    lede: "Autonomous AI agent that manages e-commerce pricing across multiple marketplaces in real time. Live production system with EUR 1.4M inventory across 3 marketplaces.",
    description:
      "5-stage pipeline: scan inventory → research signals via Tavily/ITAD/Steam → reason with Nebius Token Factory (DeepSeek-V3) + MiniMax + OpenRouter → recommend prices with confidence scoring → apply across channels.",
    cover: c(2),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["Python", "Token Factory", "DeepSeek-V3", "Tavily", "ITAD"],
    authors: [{ name: "Ionov Vitalii", handle: "Vitalio", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/kydycode/priceagent/tree/main",
    shippedAt: NB_DATE,
  },
  {
    slug: "nline",
    title: "nline",
    lede: "Uses Nebius Token Factory to deploy an OpenClaw instance in a Daytona sandbox, then uses RFC 8693 token exchange to connect to external services for tool calling.",
    description:
      "Demo connects to Linear. Extendable to Nebius Cloud with OAuth 2.0 token exchange.",
    cover: c(3),
    productFocus: ["tokenfactory", "openclaw", "aicloud"],
    technologies: ["OpenClaw", "Token Factory", "Daytona", "RFC 8693", "Linear API"],
    authors: [{ name: "Gaurav Shukla", handle: "runnerelectrode", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/runnerelectrode/nline-hack",
    shippedAt: NB_DATE,
  },
  {
    slug: "casesnipe",
    title: "CaseSnipe.ai",
    lede: "Multi-agent courtroom simulation — AI agents autonomously argue opposing sides of real legal cases while a Judge delivers verdicts. Doubles as a live LLM benchmark across Nebius open models.",
    description:
      "Swap different Nebius open LLMs into Prosecutor / Defendant / Judge roles in real time. RAG-powered precedent engine over 8,000 real court case summaries. Tavily handles live case-fact scraping. Three-panel React UI streams tool calls.",
    cover: c(4),
    productFocus: ["tokenfactory", "tavily"],
    technologies: ["React", "Token Factory", "Tavily", "RAG"],
    authors: [
      { name: "Mathew Rolf", handle: "mathewrolf1", role: "builder" },
      { name: "Brandon Tautuan", handle: "BrandonTautuan", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/brandontautuan/caseSnipe.ai",
    demoUrl: "https://youtube.com/shorts/PvvHBUdwLy4",
    shippedAt: NB_DATE,
  },
  {
    slug: "sos-answered",
    title: "SOS-Answered",
    lede: "Autonomous humanoid rescue system that uses multimodal AI — vision, audio, structural sensing from Oumi — with a fine-tuned world model on Nebius Cloud.",
    description:
      "Navigates rubble, locates trapped victims, and physically clears debris to save lives.",
    cover: c(5),
    productFocus: ["aicloud"],
    technologies: ["Python", "Nebius Cloud", "Oumi", "Vision-Language"],
    authors: [{ name: "Aksh Parekh", handle: "aparekh02", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/aparekh02/SOS-Answered-",
    shippedAt: NB_DATE,
  },
  {
    slug: "swarm-protocol",
    title: "Swarm Protocol",
    lede: "AI fleet coordination platform — the command center for deploying, organizing, and communicating with fleets of AI agents.",
    description:
      "Projects, real-time Channels, Tasks & Jobs, Agent Social Numbers (on-chain identity). Agents bring their own LLM/reasoning via OpenClaw or any framework; Swarm provides the coordination infrastructure.",
    cover: c(6),
    productFocus: ["openclaw"],
    technologies: ["TypeScript", "OpenClaw", "WebSocket"],
    authors: [
      { name: "Eric Nans", handle: "NiftyBruh", role: "builder" },
      { name: "Daniel Martinez", handle: "daniel_m", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/The-Swarm-Protocol/Swarm",
    shippedAt: NB_DATE,
  },
  {
    slug: "merit-rom",
    title: "Merit",
    lede: "Full Sim-to-Real architecture for soil analysis — Unitree G1 in a custom MuJoCo environment with a Llama-3-powered Orchestrator.",
    description:
      "Local hardware limited training depth, but the entire stack is parallelized and ready for deployment to Nebius H100 clusters via the included deployment scripts.",
    cover: c(7),
    productFocus: ["aicloud"],
    technologies: ["Python", "MuJoCo", "Llama 3", "Nebius H100"],
    authors: [{ name: "Roman Stachur", handle: "romorobo", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/romorobo/rom",
    shippedAt: NB_DATE,
  },

  // ===== Nebius.Build SF — Other Projects (no Nebius/Tavily mention) =====
  {
    slug: "cgames-cartel",
    title: "Cartel Fury — AI Red Team",
    lede: "Investigative game with AI red-team security testing — gather evidence, run undercover missions, take down a cartel with stealth and strategy.",
    description: "Dynamic combat sequences, undercover missions, and a branching narrative. Built as an AI agent red-team test environment.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Game engine", "AI Agents"],
    authors: [{ name: "Solomon Ubani", handle: "cgames", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/vsuperfranchise/cartelfurypcgame.git",
    demoUrl: "https://viewer.pandasuite.com/gb1pv674",
    shippedAt: NB_DATE,
  },
  {
    slug: "robo-chat",
    title: "Robo_chat",
    lede: "Chat with robo.",
    description: "Minimal robot chat interface submission.",
    cover: c(9),
    productFocus: ["other"],
    technologies: [],
    authors: [{ name: "Sameer Shah", handle: "sameershah21", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/sameershah21",
    shippedAt: NB_DATE,
  },
  {
    slug: "turtle",
    title: "turtle",
    lede: "Train and deploy your own tiny image model in a flash.",
    description: "Streamlined pipeline for training and deploying compact vision models.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Python", "Computer Vision"],
    authors: [
      { name: "Sam Sam", handle: "gguf", role: "builder" },
      { name: "Cal Cu", handle: "calcu", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/mochiyaki/turtle",
    shippedAt: NB_DATE,
  },
  {
    slug: "agent-human",
    title: "agent + human",
    lede: "Mocked Pi-camera stream + a bot that drives toward waypoints, logging successes and failures so the agent improves its own objective.",
    description: "A separate analysis script reads the .jsonl log and proposes improvements to the bot's behavior.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["Python", "Pi Camera"],
    authors: [{ name: "Seshadri Venkatesh", handle: "seshadribt24", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/seshadribt24/nebius",
    shippedAt: NB_DATE,
  },
  {
    slug: "skillclaw",
    title: "SkillClaw",
    lede: "Multiple AI agents learn robot manipulation by themselves in parallel — each in its own private workspace — and contribute validated skills to a shared brain.",
    description:
      "Solved skills get packaged into PRs with demo videos, reviewed by an oversight agent, and promoted to the shared library. 8 skills learned across 14 robotics benchmark tasks at the hackathon.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["Python", "Motion Planning", "Sim", "Multi-agent"],
    authors: [
      { name: "Lily Zhang", handle: "lilyzhng", role: "builder" },
      { name: "Yifei Shao", handle: "roboclaw", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/lilyzhng/SkillClaw",
    shippedAt: NB_DATE,
  },
  {
    slug: "x-g1",
    title: "X-G1",
    lede: "Rapid-iteration pipeline for the Unitree G1 — Quest 3 teleop into MuJoCo via NVIDIA Sonic, DeepLake for high-throughput training data, GR00T fine-tunes.",
    description:
      "Manual teleop completes complex pick-and-place tasks; Sonic captures high-fidelity data; GR00T runs autonomous inference. Nomadic AI surfaces failure modes for diagnosis.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["MuJoCo", "Meta Quest 3", "NVIDIA Sonic", "GR00T", "DeepLake", "Nomadic AI"],
    authors: [
      { name: "Kaushik Sivakumar", handle: "kaushik07", role: "builder" },
      { name: "Venkat Ram", handle: "venkatram", role: "builder" },
      { name: "Yifeng Wu", handle: "you", role: "builder" },
      { name: "Siyu Liu", handle: "siyulw2", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/AIBotTeachesAI/quest3-g1-teleop",
    shippedAt: NB_DATE,
  },
  {
    slug: "thinktrace",
    title: "thinktrace",
    lede: "Behavior-aware AI learning agent built around an Observe → Infer → Adapt → Remember loop.",
    description:
      "Watches how a learner naturally teaches, infers their current cognitive preference, adapts explanation + interface in real time, and stores preferences as memory for the next session.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["Python", "Behavior modeling"],
    authors: [
      { name: "Shane Li", handle: "SXL", role: "builder" },
      { name: "Chongchong Chao", handle: "chongchong", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/dliflc0617-sudo/thinktrace",
    shippedAt: NB_DATE,
  },
  {
    slug: "electricgoat-prism",
    title: "Prism",
    lede: "Private edge inference agent that refracts your biometric stream into a personal performance forecast and acts autonomously on your behalf.",
    description: "Local-first biometric monitoring with predictive forecasting.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Edge inference", "Biometric sensors"],
    authors: [{ name: "Yaxin Wang", handle: "electricgoat", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Electricgoatpod/prism",
    shippedAt: NB_DATE,
  },
  {
    slug: "conman-agents",
    title: "ConMan Agents",
    lede: "Autonomous contract intelligence for healthcare. Agents continuously monitor company contracts for expiry, clause changes, and new market developments.",
    description: "Agentic team proactively alerts companies to commercial-use-case changes and recommends next steps.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Python", "Multi-agent"],
    authors: [{ name: "Sabeen Shaikh", handle: "sabeen", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/SabeenSF/autonomous-contract-monitor",
    shippedAt: NB_DATE,
  },
  {
    slug: "horizon-min",
    title: "Horizon Min",
    lede: "Fine-tunes a vision-language model to play the classic NES Duck Hunt game from raw pixels.",
    description: "End-to-end VLM gameplay from raw pixel observations.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Python", "Vision-Language", "Reinforcement Learning"],
    authors: [{ name: "David Mayboroda", handle: "dmayboroda", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/dmayboroda/horizon_min",
    shippedAt: NB_DATE,
  },
  {
    slug: "noc-ai",
    title: "NOC AI",
    lede: "AI-powered Network Operations Center that detects, investigates, and remediates network security threats autonomously.",
    description: "Prometheus alerts fire → an LLM agent analyzes the threat and executes iptables rules via SSH — visible in a real-time chat UI.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Python", "Prometheus", "iptables", "SSH"],
    authors: [
      { name: "Mason Drake", handle: "Masons", role: "builder" },
      { name: "Ben Liu", handle: "BenLiu297", role: "builder" },
      { name: "Abby Kaur", handle: "Abbykaur146", role: "builder" },
      { name: "Huy Nguyen", handle: "Huy", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/MasonD-007/NOC_Agent",
    shippedAt: NB_DATE,
  },
  {
    slug: "ghostfeed",
    title: "ghostfeed",
    lede: "Agentically runs a social media UGC company.",
    description: "Autonomous agents handle the social UGC production loop end-to-end.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["Multi-agent"],
    authors: [{ name: "Ilia Prikhodko", handle: "ilia1", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/agi-developr/ghostfeed",
    shippedAt: NB_DATE,
  },
  {
    slug: "shadowdance",
    title: "ShadowDance",
    lede: "Single-line observability, tracing, logging, and cost-tracking from the cloud to the claw.",
    description: "Python package that drops in across the agent stack so robot-side failures don't translate into dropped balls upstream.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Python", "Tracing", "Observability"],
    authors: [{ name: "Christopher McKenzie", handle: "kristopolous", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/kristopolous/ShadowDance",
    shippedAt: NB_DATE,
  },
  {
    slug: "pool-watch",
    title: "Pool Watch",
    lede: "Privacy-first, eventually fully on-device drowning detection — captures real-time biomechanical signs and alerts you instantly.",
    description: "AI drowning detection built for the home rather than hotels and aquatic centers. No cloud, no subscription, no video leaving the property.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["Edge inference", "Pose estimation"],
    authors: [{ name: "Andrzej Firek", handle: "andrzejarturr", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/Muifrend/pool-watch",
    shippedAt: NB_DATE,
  },
  {
    slug: "jc-chaos-exploration",
    title: "JC",
    lede: "Tests whether chaos engineering — provoking robots into more chaotic exploration patterns — speeds up reinforcement learning.",
    description: "Also explores using natural language descriptors (cautious, random, aggressive, strange) to weight exploration intelligently during training.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["Python", "RL", "Sim"],
    authors: [{ name: "Janice Chan", handle: "janicechan", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/tulang-nb2022/robotics-simulation-training-hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "doctor-auditor",
    title: "Doctor Auditor",
    lede: "Local-first AI system for reviewing sensitive conversations without centralizing raw recordings or transcripts.",
    description:
      "Reverses the usual upload-everything-then-analyze pattern. Raw audio, transcripts, draft findings, and review state stay on the local machine; only approved artifacts cross the boundary.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["Local inference", "Audio processing"],
    authors: [{ name: "Robert Cordwell", handle: "discordwell", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/discordwell/doctor-auditor",
    shippedAt: NB_DATE,
  },
  {
    slug: "shopagent",
    title: "ShopAgent",
    lede: "AI shopping assistant that levels the playing field between big retailers and small businesses — searches both worlds, ranks by price, shipping, quality, and ethical sourcing.",
    description: "Makes it as easy to discover and support an independent maker as it is to click Buy Now on Amazon.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["TypeScript", "E-commerce APIs"],
    authors: [
      { name: "Victor Park", handle: "victorjhp", role: "builder" },
      { name: "Lucas Georgescu", handle: "lucasg", role: "builder" },
      { name: "Diego Viladoms", handle: "Diego_V", role: "builder" },
      { name: "Shijie Xu", handle: "shijiexu", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/jihwan-victor-park/NebiusHack",
    shippedAt: NB_DATE,
  },
  {
    slug: "hidenseek",
    title: "hideNseek",
    lede: "Robots play hide-and-seek — Seeker and Hider use vision models and RL policies to train through live feedback.",
    description: "Inspired by recent results showing LLM performance improves when trained on games — applies the same to robots.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Python", "Vision models", "RL"],
    authors: [{ name: "aTG R", handle: "r-agni", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/r-agni/hideNseek",
    shippedAt: NB_DATE,
  },
  {
    slug: "robots-for-social-good",
    title: "Robots For Social Good",
    lede: "Multimodal humanoid robotics system that learns socially beneficial behaviors from uploaded real-world human-action videos.",
    description:
      "Vision-Language-Action architecture connects perception with physical control. Predictive world model evaluates strategies before execution. Community contributors earn points when their demonstrations improve robot performance.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Python", "VLA", "Reinforcement Learning", "Unitree G1"],
    authors: [{ name: "Deon Menezes", handle: "Deonmenezes", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/deonmenezes/robotics-for-social-good",
    shippedAt: NB_DATE,
  },
  {
    slug: "ai-warehouse-fulfillment",
    title: "AI Warehouse Fulfillment",
    lede: "LLM-powered warehouse robot that reasons, routes, and adapts to chaos in real time. When rush orders flood in, it re-plans on the fly.",
    description: "Reasoning LLM owns the fulfillment station — analyzing packages, planning routing, executing step by step, then replanning under load.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Python", "LLM Reasoning"],
    authors: [{ name: "Nelson Lai", handle: "chinesepowered", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/chinesepowered/hack-neb",
    shippedAt: NB_DATE,
  },
  {
    slug: "should-work",
    title: "Should-work",
    lede: "AI agent orchestration platform for solo developers — manages a fleet of Claude Code agents that build software day and night.",
    description: "Human prioritizes issues and reviews PRs; the agents do the implementation.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Python", "Claude Code", "Multi-agent"],
    authors: [{ name: "Julaiti Alafate", handle: "julaiti", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/arapat/should-work",
    shippedAt: NB_DATE,
  },
  {
    slug: "crecerspark",
    title: "CrecerSpark",
    lede: "Autonomous robotic tour guide that navigates complex environments while providing interactive assistance to visitors.",
    description: "Intelligent obstacle avoidance plus a natural-language interface for visitor queries. Operators configure routes + destination info through a management dashboard.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["Python", "ROS", "Navigation stack"],
    authors: [
      { name: "Teodoro Alcantara", handle: "teodoro", role: "builder" },
      { name: "Mario Toribio", handle: "marioToribi0", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/marioToribi0/nebius-hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "quantbros",
    title: "Quantbros",
    lede: "Agentic investing app — profiles a user's risk preferences, picks a backtested quantitative strategy, expands it into a real stock universe, and builds a capital-weighted buy plan.",
    description: "Combines technical indicators, sentiment ranking, and risk-adjusted strategy selection.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Python", "Quantitative finance", "Multi-agent"],
    authors: [
      { name: "Carl Okpala", handle: "Carldtytan", role: "builder" },
      { name: "Shazil Farukh", handle: "Shazil", role: "builder" },
      { name: "Elbion Redenica", handle: "elbion", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/elbionredenica/agentic-quant",
    shippedAt: NB_DATE,
  },
  {
    slug: "mac-inference-swarm",
    title: "Mac Inference Swarm",
    lede: "Unlocks local inference and open-weight models through distributed autoresearch across a swarm of Macs linked through a collective intelligence cloud.",
    description: "Swarm-style coordination layer for distributed Mac-side inference jobs.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["Go", "Apple Neural Engine", "Qwen3", "Distributed inference"],
    authors: [
      { name: "Travis Cline", handle: "tmc", role: "builder" },
      { name: "Austin Baggio", handle: "Ausinbaggio", role: "builder" },
      { name: "Steven Diamond", handle: "steven-diamond", role: "builder" },
      { name: "Sai Vegasena", handle: "svegas18", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/tmc/autoresearch-go-ane/tree/autoresearch/qwen3",
    shippedAt: NB_DATE,
  },
  {
    slug: "miki-the-robot",
    title: "Miki the Robot",
    lede: "Robot companion that notices your emotional changes and offers physical + emotional support.",
    description: "A glimpse at human–robot interaction designed around emotional state recognition.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["Python", "Emotion recognition"],
    authors: [
      { name: "Linda Mao", handle: "lindamao", role: "builder" },
      { name: "Serena Yan", handle: "serenayan", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/lindamao/nebius_hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "fbx2robot",
    title: "FBX2Robot",
    lede: "Automated pipeline that translates standard 3D human animations into AI training data — instantly teaching the Unitree G1 complex, fluid movements.",
    description: "Removes hours of manual format-shuffling between motion-capture and training pipelines.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["Python", "MJLab", "FBX"],
    authors: [
      { name: "Yoha G", handle: "Yoha", role: "builder" },
      { name: "Reza Sanatkar", handle: "Rezasanatkar", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/rezasanatkar/mjlab-hackathon",
    shippedAt: NB_DATE,
  },
  {
    slug: "sous-bot",
    title: "Sous Bot",
    lede: "Assistive grocery robot for visually impaired and elderly users — picks items in a grocery store based on the meals you want.",
    description: "Vision-driven grocery navigation + selection tied to a user's meal plan.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["Python", "Computer Vision", "Robotics"],
    authors: [
      { name: "Sathvick Reddy Narahari", handle: "SathvickN", role: "builder" },
      { name: "Divya Narahari", handle: "divya", role: "builder" },
      { name: "Jyothirmai Kottu", handle: "jyothirmai", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/DivyaNarahari97/sous-bot/tree/main",
    demoUrl: "https://drive.google.com/drive/folders/1M9op3kYpl50Lv3DrdB-zrQle3t7O0HLP?usp=drive_link",
    shippedAt: NB_DATE,
  },
  {
    slug: "rocdbot",
    title: "rOCDbot",
    lede: "Uses LLM familiarity with OCD to make higher-precision robots.",
    description: "Robot sees an object out of place and loops actions until it's perfectly positioned; the trace becomes RL training data.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Python", "RL", "Robotics"],
    authors: [{ name: "Kirill Igumenshchev", handle: "kirilligum", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/kirilligum/rOCDbot-cerebral-valley-hackathon-260315",
    shippedAt: NB_DATE,
  },
  {
    slug: "niwa",
    title: "Niwa",
    lede: "Self-improving robots — continual reinforcement learning in sim for zero-shot transfer to playing Jenga.",
    description: "Sim-to-real transfer pipeline for dexterous manipulation.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Python", "RL", "Sim2Real"],
    authors: [
      { name: "Andres Nino", handle: "andres", role: "builder" },
      { name: "Alex Wu", handle: "amadeusWoo", role: "builder" },
      { name: "Ling Chow", handle: "lingchowc", role: "builder" },
      { name: "Arnaud Denis-Remillard", handle: "dr8_unix", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/TheApexWu/niwa",
    shippedAt: NB_DATE,
  },
  {
    slug: "specter",
    title: "Specter",
    lede: "Space Perception Engine for Crime, Theater, and Exploration Research — robots that see what humans miss in a crime scene, museum, or mystery game.",
    description: "Scene-understanding robot framework with multiple use-case targets.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Python", "Computer Vision"],
    authors: [{ name: "Krzysztof Barczynski", handle: "gad0lin", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/gad0lin/specter",
    shippedAt: NB_DATE,
  },
  {
    slug: "movebot",
    title: "Movebot",
    lede: "Move!",
    description: "Lightweight robot-movement demo submission.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Python"],
    authors: [{ name: "Carlos Lara", handle: "carloslara", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/LaraArias/MoveBot",
    shippedAt: NB_DATE,
  },
  {
    slug: "sideline",
    title: "SideLine",
    lede: "Modular AI sports robot — coach and ref in one. Watches gameplay live, gives technical feedback, and switches to ref mode for unbiased calls.",
    description: "Tackles the youth-sports coach/ref shortage with downloadable sport-specific modules (e.g. Tennis Coach Pro).",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["Qwen VLM", "Computer Vision"],
    authors: [
      { name: "Kruthik Hulisandra", handle: "kruthik", role: "builder" },
      { name: "Vissh B", handle: "vissh30", role: "builder" },
      { name: "Vivek Gopal Ramaswamy", handle: "vivekgr92", role: "builder" },
      { name: "Ravinder Jilkapally", handle: "jravinder", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/nebiusbuildsf/sideline",
    demoUrl: "https://sideline-beige.vercel.app/",
    shippedAt: NB_DATE,
  },
  {
    slug: "dayops",
    title: "dayops",
    lede: "Minimal backend for voice-memo planning into Google Calendar.",
    description: "Voice in, calendar out. Compact integration layer.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Python", "Google Calendar API"],
    authors: [{ name: "Kian Kyars", handle: "kian", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/kiankyars/dayops",
    shippedAt: NB_DATE,
  },
  {
    slug: "splatica",
    title: "Splatica",
    lede: "Jumping into reality — from live room video to world-modeled robotic control in Isaac Sim.",
    description: "Pipeline from real-world video capture to physics-grounded robotic control in simulation.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["Isaac Sim", "Computer Vision", "World Models"],
    authors: [{ name: "Andrey Shelomentsev", handle: "Shelomen", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/ashelomentsev/physical",
    shippedAt: NB_DATE,
  },
  {
    slug: "hooke",
    title: "Hooke",
    lede: "Research assistant for bench scientists — turns a scientific question into a usable starting point with literature, computational analysis, and model-based insight.",
    description: "Cuts hours of manual paper-searching and tool-stitching down to one brief that supports the decision on the next experiment.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["Python", "LLM Research"],
    authors: [{ name: "Zayd Khan", handle: "Cold", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/zaydiscold/hooke-preview",
    shippedAt: NB_DATE,
  },
  {
    slug: "hummingbird",
    title: "HUMMINGBIRD",
    lede: "Clinical-trial biospecimen tracking — instantly identifies samples submitted but never resulted, with regulatory context and an audit trail.",
    description: "Replaces the manual Excel workflow that vendors currently use to chase missing results.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["Python", "Clinical-trial data"],
    authors: [{ name: "Lyona", handle: "Lyona", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/tiyembelabs",
    shippedAt: NB_DATE,
  },
  {
    slug: "pulse",
    title: "Pulse",
    lede: "Mobile-first AI app — send an AI agent instead of explaining context. Package an agent with voice notes, documents, and calendar availability, then send it via link.",
    description: "Recipients chat with the agent to ask questions, understand decisions, or schedule follow-ups. One-tap voice capture; strict permission control.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["TypeScript", "React Native", "WebRTC"],
    authors: [
      { name: "Yu Chen", handle: "Waterdog", role: "builder" },
      { name: "Eason W", handle: "easonw", role: "builder" },
      { name: "Yi Li", handle: "LeoYili", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/waterdoog/agent-messenger.git",
    demoUrl: "https://aicoo.lovable.app/",
    shippedAt: NB_DATE,
  },
  {
    slug: "robot-agent-mac",
    title: "Robot Agent (Mac)",
    lede: "Mac app that uses an LLM to make tool calls to move a simulated robot arm.",
    description: "Lightweight native shell over the simulated-arm control surface.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Swift", "macOS", "LLM tools"],
    authors: [
      { name: "Brennan Stehling", handle: "brennanMKE", role: "builder" },
      { name: "Lisa Pederson", handle: "LisaPede", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/brennanMKE/RobotAgent",
    shippedAt: NB_DATE,
  },
  {
    slug: "kleiner-bot",
    title: "Kleiner Bot",
    lede: "Teach robots emotion by reading my own. (Withdrawn — author didn't have time to record.)",
    description: "Reachy emotion-mirroring submission. Author withdrew before final demo.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Reachy", "Emotion mirroring"],
    authors: [{ name: "Tor", handle: "tor", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/hagemt/reachy-emotes",
    shippedAt: NB_DATE,
  },
  {
    slug: "control-spaces",
    title: "Control Spaces",
    lede: "Ambient cameras across a workspace passively observe day-to-day human activities and convert the continuous visual stream into structured training data for robots.",
    description: "Robots learn by watching people do their jobs — no one stops to \"teach\" the robot.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Computer Vision", "Activity recognition"],
    authors: [{ name: "Sudhir D", handle: "dadisudhir", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/dadisudhir/control-spaces-training",
    shippedAt: NB_DATE,
  },
  {
    slug: "aw3-openeye",
    title: "AW3 OpenEye",
    lede: "Open-source digital vision CLI tool and dashboard.",
    description: "CLI-first vision-stack utility with a dashboard layer.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Computer Vision", "CLI"],
    authors: [{ name: "William Schulz", handle: "wschulz", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/aw3-technology/openeye.sh",
    shippedAt: NB_DATE,
  },
  {
    slug: "trinkss",
    title: "trinkss",
    lede: "Robot-Ready Workcell Compiler — inspects a messy workspace, decides what operational structure is missing, and prints it.",
    description: "Bridges the gap between manual chaos and full robotic automation by making spaces immediately legible to unskilled humans and cheap robots.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["Computer Vision", "3D printing"],
    authors: [{ name: "Sa Sa", handle: "sasa", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://gitlab.com/trinkss-group/trinkss-project/",
    shippedAt: NB_DATE,
  },
  {
    slug: "clonesmp",
    title: "cloneSMP",
    lede: "Manhunt by AI.",
    description: "Multiplayer survival manhunt with AI-driven players.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["TypeScript", "Game AI"],
    authors: [
      { name: "Sean Chiu", handle: "seanchiuai", role: "builder" },
      { name: "Vihaan Shringi", handle: "vhn1s", role: "builder" },
    ],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/seanchiuai/cloneSMP/",
    shippedAt: NB_DATE,
  },
  {
    slug: "zippling",
    title: "zippling",
    lede: "Agentic e-commerce customer-service resolution platform — handles support resolution agentically based on platform policies, text, and vision.",
    description: "Reduces human support overhead by routing more cases through policy-aware autonomous agents.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["TypeScript", "Vision-Language", "Agentic"],
    authors: [{ name: "Parth Gala", handle: "parthgala", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/ParthGala2k/zippling_ai_commerce",
    shippedAt: NB_DATE,
  },
  {
    slug: "labpilot",
    title: "LabPilot",
    lede: "AI copilot for experiment optimization in pharma R&D labs — helps scientists decide the next best experiment.",
    description: "Combines a surrogate model trained on historical experiment data, adaptive decision policies (UCB / contextual LinUCB), and literature evidence for trust + interpretability.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["Python", "Surrogate Models", "Bandit Algorithms"],
    authors: [{ name: "Rajat Patel", handle: "rajathpatel23", role: "builder" }],
    eventTitle: NB_HACK,
    githubUrl: "https://github.com/rajathpatel23/LabPilot",
    demoUrl: "https://elevenlabs.io/app/studio/gX7HGkEFzhr8aXblsA0J",
    shippedAt: NB_DATE,
  },

  // ===== JetBrains × OpenAI Codex — Winners + Finalists =====
  {
    slug: "thinking-hyperreasoning",
    title: "thinking — Rainbow RL coding agent",
    lede: "Self-healing coding agent that searches over compact DSL implementation plans before generating code. Rainbow RL controls which branch to refine, compile, backtrack, or terminate.",
    description: "On a held-out synthetic benchmark, Rainbow with Gemma E2B matches Codex 5.4 Low's 80% solve rate using ~140× fewer tokens and 4× faster — entirely on a single M3 MacBook Pro.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["Python", "Rainbow RL", "Gemma E2B", "Codex"],
    authors: [{ name: "Aditya Mangalampalli", handle: "amangalampalli", role: "builder" }],
    eventTitle: JB_HACK,
    awards: [{ label: "Winner", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/amangalampalli/hyperreasoning",
    shippedAt: JB_DATE,
  },
  {
    slug: "scopecreep",
    title: "Scopecreep",
    lede: "Turns your JetBrains IDE into an agentic hardware test bench — describe a test in plain English, an AI agent writes Python, runs it against real lab instruments, and drops results back in the project.",
    description: "Bundles a Python sidecar that drives Digilent Analog Discovery and FNIRSI DPS-150 over REST. Supabase-backed instrument-profile memory, OpenAI function-calling agent, in-prompt + driver-level safety rails.",
    cover: c(4),
    productFocus: ["tokenfactory"],
    technologies: ["Kotlin", "Python", "FastAPI", "Nebius", "Supabase", "OpenAI"],
    authors: [
      { name: "Bhavik Sheoran", handle: "Bhavik", role: "builder" },
      { name: "Kenneth Ross", handle: "kross", role: "builder" },
      { name: "Roman Javadyan", handle: "romanj_lm317", role: "builder" },
      { name: "Joon Im", handle: "joon_the_goon", role: "builder" },
    ],
    eventTitle: JB_HACK,
    awards: [{ label: "Runner-up", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/BhavikFTW/Scopecreep",
    demoUrl: "https://www.youtube.com/shorts/x56vTEeutgk",
    shippedAt: JB_DATE,
  },
  {
    slug: "mesh-code",
    title: "Mesh Code",
    lede: "Shared session state for coding agents — install mesh-code-mcp in any IDE and any agent (Claude / Cursor / Codex) sees the same feature card, event ledger, and decisions.",
    description: "Close one laptop, open another — resume mid-sentence with no cold boot. MCP server for cross-agent shared state.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["TypeScript", "MCP", "Supabase", "Vercel", "Redis", "Codex"],
    authors: [
      { name: "Ayush Ojha", handle: "ayushojha", role: "builder" },
      { name: "Coco Cao", handle: "cococao", role: "builder" },
      { name: "Kush Ise", handle: "KUSH2704", role: "builder" },
      { name: "AL DRAM", handle: "aldram", role: "builder" },
    ],
    eventTitle: JB_HACK,
    awards: [{ label: "3rd Place", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/ayushozha/mesh-code",
    demoUrl: "https://drive.google.com/drive/folders/1VQX9AMkWVQdGgCLk_IBV594u1Pa2kE-9?usp=sharing",
    shippedAt: JB_DATE,
  },
  {
    slug: "latent-signal-periscope",
    title: "Periscope — Latent Signal",
    lede: "Local-first viewer that shows exactly what's in your coding agent's context window, turn by turn, and tells you what to do about it.",
    description: "Visualizes context grouped by turn — tool outputs, file reads, stale plans. Surfaces bloat, repetition, and rot. Recommends compact / branch off / start fresh / rewind. Lives inside JetBrains as a plugin.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Go", "SQLite FTS5", "Svelte 5", "JetBrains Platform SDK", "Codex"],
    authors: [
      { name: "Ann Catherine Jose", handle: "annjose", role: "builder" },
      { name: "George Chiramattel", handle: "georgeck", role: "builder" },
    ],
    eventTitle: JB_HACK,
    awards: [{ label: "Finalist", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/latentsignal-org/periscope",
    shippedAt: JB_DATE,
  },
  {
    slug: "secureloop",
    title: "SecureLoop",
    lede: "Turns production Sentry alerts into Codex-generated, sandbox-tested, human-approved fixes inside JetBrains.",
    description: "Pulls Sentry context, drafts a fix with Codex, runs it in a sandbox, asks a human for approval, and ships the patch back into the IDE.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Kotlin", "Codex", "Sentry", "Vercel", "Supabase"],
    authors: [
      { name: "Peyton Li", handle: "peli", role: "builder" },
      { name: "Abhiram Yadu Sribhashyam", handle: "abhiram", role: "builder" },
      { name: "Rahul Marri", handle: "rm33", role: "builder" },
    ],
    eventTitle: JB_HACK,
    awards: [{ label: "Finalist", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/PeytonLi/JBHack",
    shippedAt: JB_DATE,
  },
  {
    slug: "pinpoint",
    title: "Pinpoint",
    lede: "Visual annotation overlay for frontend review — also helps pinpoint things in complex software.",
    description: "Click-to-annotate overlay that captures visual context on top of any frontend.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["TypeScript", "Codex", "JetBrains Plugin"],
    authors: [{ name: "Het Patel", handle: "HetPatelx", role: "builder" }],
    eventTitle: JB_HACK,
    awards: [{ label: "Finalist", sponsor: "JetBrains × OpenAI" }],
    githubUrl: "https://github.com/hetpatel-11/Pinpoint.git",
    demoUrl: "https://cap.so/s/ax0mz355b8h3076",
    shippedAt: JB_DATE,
  },

  // ===== JetBrains × OpenAI Codex — Other Projects (Nebius-using) =====
  {
    slug: "redgreen",
    title: "RedGreen",
    lede: "Turns the JetBrains IDE into a self-healing runtime. When the debugger trips a runtime exception, four models race in parallel — each steered by a different hypothesis lens.",
    description: "Each candidate produces a failing test + patch + rationale, then has to survive Runner, Peers, Regression, and Review gates before reaching the developer. Per-codebase leaderboard biases future runs toward known winners.",
    cover: c(9),
    productFocus: ["tokenfactory"],
    technologies: ["Kotlin", "JetBrains Platform SDK", "Docker", "Nebius", "Vercel", "Supabase"],
    authors: [
      { name: "Rudy A", handle: "rudy99", role: "builder" },
      { name: "Likhit Juttada", handle: "likhitjuttada", role: "builder" },
      { name: "Param Shah", handle: "PesseJinkman", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/rudranshagrawal/redgreen",
    shippedAt: JB_DATE,
  },
  {
    slug: "chainmail-council",
    title: "ChainMail Council",
    lede: "Before any AI-generated change touches your codebase, a council of specialized models deliberates and votes. Decisions are hash-chained to a sovereign audit log.",
    description: "Codex inside JetBrains selects the right agents and fires them in parallel against Nebius Token Factory (Qwen3 235B, Nemotron Ultra 253B, Nemotron 120B). FIDO2 hardware key verification. Gemma synthesizes consensus on a sovereign VM.",
    cover: c(0),
    productFocus: ["tokenfactory", "openclaw", "aicloud"],
    technologies: ["JetBrains", "Codex", "Token Factory", "Nebius H100", "OpenClaw", "FIDO2", "Supabase"],
    authors: [{ name: "Daniel Kaneshiro", handle: "Cre808ive", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/ChainMailGlobal/chainmail-council",
    shippedAt: JB_DATE,
  },
  {
    slug: "rodex",
    title: "Rodex IDE",
    lede: "Cursor-style IDE that uses 4 AI agents — powered by Nebius coding model + Blaxel sandboxes — to perform real-time security analysis, bug detection, and autonomous fix application on Python codebases.",
    description: "Multi-agent pipeline operating directly on the open file tree, gated by user approval.",
    cover: c(1),
    productFocus: ["tokenfactory"],
    technologies: ["TypeScript", "Nebius Coding Model", "Blaxel Sandbox", "Clerk", "Vercel"],
    authors: [
      { name: "Yuvraj Gupta", handle: "Yuvraj", role: "builder" },
      { name: "Pramod Thebe", handle: "pthebe", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/YuvrajGupta1808/Rodex-IDE",
    shippedAt: JB_DATE,
  },
  {
    slug: "omnidev",
    title: "OmniDev",
    lede: "Background coding agent you can hear, talk to, and carry with you. Spins up a Vercel Sandbox, clones a branch, plans, edits, opens a PR — narrating its reasoning through Gemini Live.",
    description: "Redirect it mid-flight by voice. When it hits a blocker, it phones you via Twilio so you can resolve it conversationally. Native macOS menu-bar shell + Tauri desktop. Built on Vercel Sandboxes, Supabase, GitHub App, and Nebius-hosted OSS models.",
    cover: c(2),
    productFocus: ["tokenfactory"],
    technologies: ["TypeScript", "Vercel Sandbox", "Supabase", "Nebius", "Twilio", "Gemini Live", "Tauri"],
    authors: [
      { name: "Ming Lu", handle: "sleepy", role: "builder" },
      { name: "Rithvik Manikandan", handle: "rithm84", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/rithm84/OmniDev",
    shippedAt: JB_DATE,
  },
  {
    slug: "memorylint",
    title: "MemoryLint",
    lede: "IDE-native trust and governance layer for AI-written code in JetBrains. Sits between the agent and the keystroke, deciding what agents can remember, recall, and act on — and proving every decision.",
    description: "AuthZed/SpiceDB for Zanzibar-style authorization on governed recall. Nebius Token Factory for multi-model consensus on high-severity decisions. Supabase for evidence packs. Neo4j for provenance + blast-radius traversal.",
    cover: c(3),
    productFocus: ["tokenfactory"],
    technologies: ["Kotlin", "FastAPI", "Next.js", "Nebius Token Factory", "AuthZed/SpiceDB", "Supabase", "Neo4j", "Codex"],
    authors: [{ name: "Sidra Miconi", handle: "Sidra", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Sidra/memorylint-hack",
    shippedAt: JB_DATE,
  },
  {
    slug: "jetbio",
    title: "JetBio",
    lede: "IDE reimagined for computational biology — treats biological correctness as a first-class debugging target.",
    description: "BioTrace traces a bad result to root cause. BioFuzz stress-tests pipelines with synthetic biological edge cases. BioReview reviews analysis code like a peer reviewer would. Uses ConTree's pipeline branching.",
    cover: c(4),
    productFocus: ["tokenfactory", "aicloud"],
    technologies: ["Python", "Nebius", "ConTree", "JetBrains"],
    authors: [{ name: "Mahtabin Rodela", handle: "mahtabin", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/AUW160150/JetBrain",
    shippedAt: JB_DATE,
  },
  {
    slug: "code-lingua",
    title: "Code Lingua",
    lede: "Code with your voice — and not in English. Custom model for coding in Tamil, Hindi, and Bengali.",
    description: "IntelliJ plugin records voice (Alt+Shift+R / Alt+Shift+S), backend generates a prompt and runs codex exec against the project root.",
    cover: c(5),
    productFocus: ["tokenfactory"],
    technologies: ["Kotlin", "Nebius", "Codex", "Supabase", "Vercel"],
    authors: [
      { name: "Kaushik Sivakumar", handle: "kaushik07", role: "builder" },
      { name: "Mahtabin Rodela", handle: "mahtabin", role: "builder" },
      { name: "Raka Kumar", handle: "raka", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/KaushikSiva/lingua-code",
    shippedAt: JB_DATE,
  },

  // ===== JetBrains × OpenAI Codex — Other Projects (no Nebius/Tavily) =====
  {
    slug: "runtimefix",
    title: "RuntimeFix",
    lede: "Debugger-aware bug-fixing agent that actually sees what broke.",
    description: "Plugin that grabs the runtime state when an exception trips and routes it to a fix-suggestion agent.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Kotlin", "JetBrains", "LLM debugger"],
    authors: [{ name: "Nelson Lai", handle: "chinesepowered", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/chinesepowered/hack-jetbrains",
    shippedAt: JB_DATE,
  },
  {
    slug: "dronomy-ros-migration",
    title: "dronomy — ROS1→ROS2 migration agent",
    lede: "AI agent that deeply understands a ROS1 codebase and generates the complete ROS2 migration at scale — handling thousands of breaking API changes.",
    description: "Migrated the KumarRobotics MAV stack: 44 packages, 3,773 findings, 28/28 packages building clean. Every patch validated by a real colcon build inside ROS2 Jazzy Docker. JetBrains plugin surfaces per-package status + diffs.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Python", "ROS1", "ROS2", "colcon", "Docker", "o4-mini"],
    authors: [{ name: "Suvasis Mukherjee", handle: "suvasis", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/dronomyio/ros1_to_ros2_migration_agent.git",
    shippedAt: JB_DATE,
  },
  {
    slug: "doubley-react-flow",
    title: "DoubleY — React Flow Visualizer",
    lede: "IntelliJ plugin that scans a React project and draws an interactive component graph in a side panel.",
    description: "Beginners see parent–child structure at a glance and jump to source from nodes — faster mental map for onboarding and debugging.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["Kotlin", "JetBrains", "React parsing"],
    authors: [
      { name: "Yue Chen", handle: "yuechen", role: "builder" },
      { name: "Yi Zhang", handle: "YiZhang", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/YiZhang527/react-flow-visualizer",
    shippedAt: JB_DATE,
  },
  {
    slug: "goldfish",
    title: "goldfish",
    lede: "Evolving AI agent that learns from every interaction — picks up new skills on the fly and expands through a modular ecosystem of tools.",
    description: "Persistent understanding of user preferences. Plugin for JetBrains IDEs makes coding, debugging, and reviewing large codebases lighter-weight.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["Python", "JetBrains Plugin"],
    authors: [{ name: "Cal Cu", handle: "calcu", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/calcuis/goldfish",
    shippedAt: JB_DATE,
  },
  {
    slug: "lintropy",
    title: "Lintropy",
    lede: "Rust-based linter + LSP that lets you define repo-specific rules in YAML — enforce conventions generic linters can't, like \"API handlers must live under src/api/\".",
    description: "Tree-sitter for structural matching + regex for text matching. Runs in CLI, CI, editors, and coding agents. Bundled SKILL.md teaches agents to author rules and fix their own violations in a write → lint → fix loop.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Rust", "tree-sitter", "LSP", "JetBrains", "Codex"],
    authors: [
      { name: "Jelle Maas", handle: "Typiqally", role: "builder" },
      { name: "Rens Dijk", handle: "rens", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Typiqally/lintropy",
    shippedAt: JB_DATE,
  },
  {
    slug: "speedrunner",
    title: "SpeedRunner",
    lede: "AI-assisted, human-governed incident response — cuts P1 outage response and resolution times in half by eliminating triage slop.",
    description: "Codebase version compare, root-cause agents, log/release record review, patch generation, unit/QA/stage tests, two-person sign-off, controlled production rollout. Every step audited.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["JetBrains", "Incident response", "Multi-agent"],
    authors: [{ name: "Irina Poslavsky", handle: "msirina", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/kotrie/nopCommerce",
    shippedAt: JB_DATE,
  },
  {
    slug: "phantom-pr-autopilot",
    title: "Phantom — PR Autopilot",
    lede: "AI architect for modern dev teams — analyzes every PR for architectural integrity, deployment risk, and technical debt instead of nits.",
    description: "Risk scoring (Blast Radius), senior-level architectural insights, test gap analysis, and a Ghost Writer that produces professional PR descriptions.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Codex", "Vercel"],
    authors: [{ name: "Vince R", handle: "vjr", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/lgcy-official/Phatom-PR-Autopilot",
    demoUrl: "https://kommodo.ai/recordings/lRqVex745It2AtQ34DuE",
    shippedAt: JB_DATE,
  },
  {
    slug: "guardia",
    title: "Guardia",
    lede: "Deployment risk copilot in JetBrains — proactively alerts about deploy risks grounded in DataDog data and prior incident history.",
    description: "Pinpoints the exact line of code that would break the existing codebase before a PR is pushed; auto-heals and explains why.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["JetBrains", "OpenAI", "Codex", "DataDog", "Supabase"],
    authors: [{ name: "Steven Yang", handle: "stevenybuilder", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/stevenybuilder/guardia",
    shippedAt: JB_DATE,
  },
  {
    slug: "rankguard",
    title: "Team RankGuard",
    lede: "Context-aware adversarial testing for ML and ranking pipelines, built directly into JetBrains via External Tools.",
    description: "Right-click context menu fires a Python agent that generates adversarial test cases against the active editor's matrix code. GPT-4o-driven adversarial reasoning, pytest + numpy under the hood.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["Python", "GPT-4o", "pytest", "numpy", "JetBrains External Tools"],
    authors: [{ name: "Isha S", handle: "isha", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/GenieCode/rankguard-jetbrains-hackathon/",
    shippedAt: JB_DATE,
  },
  {
    slug: "sky-is-blue-roofline",
    title: "Sky is Blue — Roofline Analyzer",
    lede: "VS Code extension that shows what's bottlenecking your transformer — compute or memory — in real time, right inside your editor.",
    description: "Auto-detects model architecture, plots every transformer op on a live roofline chart, and identifies wasted GPU. Supports TPU v4/v5e/v5p, A100, H100, H200. GPT-4o suggests batch size, precision, parallelism strategy from live numbers.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Python", "VS Code Extension", "GPT-4o", "Roofline analysis"],
    authors: [{ name: "Sai Kavya", handle: "skreddy", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/MarthalaSaiKavya/roofline-analyzer",
    demoUrl: "https://drive.google.com/file/d/1zWVojiC_Y9Y-dSytbHAZrP1kb1K_n_KV/view",
    shippedAt: JB_DATE,
  },
  {
    slug: "hindsight",
    title: "Hindsight",
    lede: "Local-first memory layer for AI coding — tracks coding attempts inside JetBrains (edits, test runs, failures, reverts) and turns them into structured attempt history.",
    description: "MCP integration lets agents query prior attempts before trying a new fix. Syncs to Supabase + a dashboard for cross-session history and audit.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Supabase", "Vercel", "MCP"],
    authors: [
      { name: "Shazil Farukh", handle: "Shazil", role: "builder" },
      { name: "Carl Okpala", handle: "Carldtytan", role: "builder" },
      { name: "Elbion Redenica", handle: "elbion", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/elbionredenica/hindsight",
    shippedAt: JB_DATE,
  },
  {
    slug: "quasa0-voicecodex",
    title: "VoiceCodex",
    lede: "JetBrains plugin (WebStorm) that turns the IDE into a hands-free conversational coding partner — talk naturally, watch Codex do the work.",
    description: "OpenAI Realtime API + Codex; hands stay off the keyboard while the agent writes and edits.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Kotlin", "OpenAI Realtime API", "OpenAI Codex", "WebStorm"],
    authors: [{ name: "Anatolii Zhukovskyi", handle: "quasa0", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/quasa0/VoiceCodex",
    demoUrl: "https://youtube.com/shorts/NooDSUSjDvs",
    shippedAt: JB_DATE,
  },
  {
    slug: "tatergang-plannotator",
    title: "Plannotator Live — TaterGang",
    lede: "Collaborative planning review surface for agentic engineering — Plan Reviews where humans + agents align on the plan before code is written.",
    description: "Built from scratch at the hackathon. End-to-end zero-knowledge encryption so plans stay private.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["TypeScript", "Codex", "End-to-end encryption"],
    authors: [{ name: "Michael Ramos", handle: "backnotprop", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/backnotprop/plannotator/pull/591",
    shippedAt: JB_DATE,
  },
  {
    slug: "true-verification",
    title: "TRUE",
    lede: "No review bottlenecks, no merge conflicts, no broken tests — every change is verified before it lands.",
    description: "JetBrains plugin brings verification-gated Codex runs into the IDE. Vercel hosts the dashboard + SSE run-streaming API. Supabase mirrors the RunLedger for cross-session history.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Codex", "Vercel", "Supabase", "SSE"],
    authors: [
      { name: "Yahya Alhinai", handle: "yhinai", role: "builder" },
      { name: "Maxime Boucher", handle: "mxboucher", role: "builder" },
      { name: "Jie Cui", handle: "JewelrySway", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/yhinai/true",
    shippedAt: JB_DATE,
  },
  {
    slug: "dav-spatial-plugin",
    title: "Dav Yaginuma — IntelliJ Spatial Plugin",
    lede: "Spatial pane in the IDE plus MCP commands that let an agent render anything in 3D — project structure, algorithm walkthroughs, narrated visualizations.",
    description: "Camera movement + speech create a narrative; the spatial visualization is interactive. Works with WebXR for immersive viewing.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["Kotlin", "JetBrains", "Codex", "WebXR", "MCP"],
    authors: [{ name: "Dav Yaginuma", handle: "dav", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/dav/IntelliJSpatialPlugin",
    demoUrl: "https://youtu.be/JSIVpX6DGY0",
    shippedAt: JB_DATE,
  },
  {
    slug: "shipsec-local",
    title: "ShipSec Local",
    lede: "Local-first security review plugin + workflow for Codex. Builds a repo-wide security model, saves a trusted baseline, then flags newly introduced attack vectors and widened trust boundaries.",
    description: "Clean-room verification in Docker so teams can run the same review flow in an isolated Codex environment.",
    cover: c(1),
    productFocus: ["other"],
    technologies: ["Kotlin", "Codex", "JetBrains", "Docker"],
    authors: [{ name: "Pranjal Paliwal", handle: "betterclever", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/betterclever/shipsec-local",
    shippedAt: JB_DATE,
  },
  {
    slug: "af-forward-deployed",
    title: "AF* — AI Forward Deployed Engineer",
    lede: "AI Forward Deployed Engineer that helps organizations onboard unknown systems and work with multiple systems.",
    description: "Currently focused on ERP data ingestion — multiple agents research, iterate, and then deploy the ingestion pipeline automatically.",
    cover: c(2),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Vercel", "Codex", "Supabase"],
    authors: [
      { name: "Div Agarwal", handle: "div_vi", role: "builder" },
      { name: "James Chen", handle: "yagidagi", role: "builder" },
      { name: "Haarish M K", handle: "haarish", role: "builder" },
      { name: "Jerry Shu", handle: "jerry", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Lendica-PlayGround/erp-data-ingestion",
    shippedAt: JB_DATE,
  },
  {
    slug: "visualcode",
    title: "VisualCode",
    lede: "Turns a user request into a structured plan and visualizes it as a growing tree graph — intuitive view of what an AI agent is building, especially for non-technical users.",
    description: "Breaks work into branches so users can follow the agent's thinking from idea to implementation.",
    cover: c(3),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains"],
    authors: [{ name: "Barkley Dai", handle: "charlesdegaulle", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/degaulle/visualcode",
    demoUrl: "https://bit.ly/visualcodevideo",
    shippedAt: JB_DATE,
  },
  {
    slug: "nikhils-deckcreator",
    title: "DeckCreator",
    lede: "Bridges business workflows and software development — turns an Excel + PowerPoint reference into a structured executive deck, and converts feature requests into actionable code tickets.",
    description: "Non-technical users get auto-generated decks; developers get an AI agent that proposes diffs, applies approved changes, and deploys.",
    cover: c(4),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains PyCharm", "Vercel", "Codex"],
    authors: [{ name: "Nikhil Tarigonda", handle: "Nikhilt2910", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Nikhilt2910/deckcreator/",
    demoUrl: "https://deckcreator-yjsv.vercel.app/",
    shippedAt: JB_DATE,
  },
  {
    slug: "blueprint-berkeley-baris",
    title: "Blueprint",
    lede: "PyCharm plugin that helps developers plan a codebase before implementing it — clearer architectural overview before AI starts generating code.",
    description: "Analyzes an existing project into editable Mermaid UML or sketches a fresh design via an AI-assisted side chat. Converts the design into scoped, dependency-aware implementation nodes with planning, codegen, review, diff preview, validation, apply.",
    cover: c(5),
    productFocus: ["other"],
    technologies: ["Kotlin", "JetBrains", "Mermaid UML"],
    authors: [
      { name: "Noah Lund Syrdal", handle: "noahls", role: "builder" },
      { name: "Lars Talian Stangebye-Hansen", handle: "larstalian", role: "builder" },
      { name: "Anders Vestrum", handle: "anders", role: "builder" },
      { name: "Jorgen Bergh", handle: "jorgbergh", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/NoahLundSyrdal/blueprint",
    shippedAt: JB_DATE,
  },
  {
    slug: "artificial-sixy",
    title: "Adaptive Change Harness",
    lede: "Self-evolving verification + repair system for real codebases — wraps models inside a reproducible evidence loop instead of trusting their output.",
    description: "Ingests a repo, discovers a real latent failure, saves the exact repro, repairs it with grounded context, reruns deterministic validation, then converts validated fixes into reusable repair skills.",
    cover: c(6),
    productFocus: ["other"],
    technologies: ["Python", "JetBrains", "Vercel", "OpenAI"],
    authors: [{ name: "Hades Li", handle: "hades", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Hades-HY-LI/Adaptive-Change-Harness",
    shippedAt: JB_DATE,
  },
  {
    slug: "bug-bounty-research",
    title: "Bug Bounty — AI Agent Defense Research",
    lede: "Research project on how dangerous AI agents can be to the software world — and what we can do to mitigate it.",
    description: "Honeypots and mitigation systems for AI agents, plus ethical attack patterns to learn from. Surfaces danger level and live mitigation as it happens.",
    cover: c(7),
    productFocus: ["other"],
    technologies: ["Python", "JetBrains", "Vercel", "Supabase"],
    authors: [{ name: "Deon Menezes", handle: "Deon_Menezes", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/deonmenezes/bug-bounty",
    shippedAt: JB_DATE,
  },
  {
    slug: "safevibing",
    title: "Safevibing",
    lede: "Reviews vibe-coded repository output for security, design quality, explainability, and engineering metrics.",
    description: "End-to-end review surface focused on code that's been generated quickly and needs a serious second look.",
    cover: c(8),
    productFocus: ["other"],
    technologies: ["JetBrains", "Vercel", "Codex"],
    authors: [{ name: "Emahatsion Issac", handle: "issac", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/amahaeitbit/saveVibing",
    shippedAt: JB_DATE,
  },
  {
    slug: "volta",
    title: "Volta",
    lede: "Skills for coding agents to run code systematically.",
    description: "Skill library that gives coding agents a more disciplined execution loop.",
    cover: c(9),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Vercel", "Supabase"],
    authors: [{ name: "Saurabh Khire", handle: "saurabhkhire", role: "builder" }],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/Saurabhkhire/vibe-coding-agent-extension",
    shippedAt: JB_DATE,
  },
  {
    slug: "cue",
    title: "Cue",
    lede: "The coding agent to solve all problems — as many tools as you need, wrapped in a UI handcrafted with taste.",
    description: "Your next move, on cue.",
    cover: c(0),
    productFocus: ["other"],
    technologies: ["TypeScript", "JetBrains", "Vercel", "OpenAI Codex"],
    authors: [
      { name: "Sajjaad Farzad", handle: "themackabu", role: "builder" },
      { name: "Rahul Suthar", handle: "Suthar_rahul", role: "builder" },
      { name: "Mateo Alado", handle: "mateo", role: "builder" },
      { name: "Darien Chau", handle: "darien", role: "builder" },
    ],
    eventTitle: JB_HACK,
    githubUrl: "https://github.com/sf-tools/cue",
    shippedAt: JB_DATE,
  },
];

// -- helpers -----------------------------------------------------------------

export type AwardFilter = "ALL" | "AWARDED" | "OFFICIAL";

export function projectAuthorRoleLabel(role: ProjectAuthorRole) {
  return role.charAt(0).toUpperCase() + role.slice(1);
}

export const projectTechs = Array.from(
  new Set(projects.flatMap((p) => p.technologies)),
).sort();

export const projectEvents = Array.from(
  new Map(
    projects
      .filter((p) => p.eventId && p.eventTitle)
      .map((p) => [p.eventId!, p.eventTitle!]),
  ).entries(),
);

export const findProject = (slug: string) => projects.find((p) => p.slug === slug);
